import type { AuditEvent, HubState, Member, Report, WorkItem } from '../shared/types.js';
import { reportingPeriod } from '../shared/reporting.js';

/** Fictional demonstration data only. No I/O, random IDs, or ambient clock reads. */
export function createSeedState(now = new Date()): HubState {
  if (!Number.isFinite(now.getTime())) throw new Error('A valid seed date is required.');
  const hour = 3_600_000;
  const day = 24 * hour;
  const at = (hours: number) => new Date(now.getTime() + hours * hour).toISOString();
  const date = (days: number) => new Date(now.getTime() + days * day + 4 * hour).toISOString().slice(0, 10);
  const nextThursday = new Date(reportingPeriod(now, 'Asia/Dubai', 12).endAt);
  const cutoff = (weeks: number) => new Date(nextThursday.getTime() + weeks * 7 * day).toISOString();
  const periodEnd = (weeks: number) => cutoff(weeks).slice(0, 10);
  const v = (id: string, hours = -8, version = 1) => ({ id, version, updatedAt: at(hours) });
  const evidence = (name: string) => `https://example.com/demo/evidence/${name}`;
  const allStreams = ['ws-assistant', 'ws-data', 'ws-evaluation'];
  const members: Member[] = [
    { id: 'pmo-nadia', name: 'Nadia Rahman', initials: 'NR', role: 'pmo', title: 'PMO · phase two', color: '#6366f1', workstreamIds: allStreams, canApproveReports: false },
    { id: 'exec-omar', name: 'Omar Haddad', initials: 'OH', role: 'executive', title: 'Delivery manager', color: '#334155', workstreamIds: allStreams, canApproveReports: true },
    { id: 'lead-leila', name: 'Leila Mansour', initials: 'LM', role: 'lead', title: 'AI assistant lead', color: '#7c3aed', workstreamIds: ['ws-assistant'], canApproveReports: false },
    { id: 'lead-arjun', name: 'Arjun Mehta', initials: 'AM', role: 'lead', title: 'Data platform lead', color: '#0891b2', workstreamIds: ['ws-data'], canApproveReports: false },
    { id: 'lead-sara', name: 'Sara Chen', initials: 'SC', role: 'lead', title: 'Evaluation lead', color: '#ea580c', workstreamIds: ['ws-evaluation'], canApproveReports: false },
    { id: 'dev-yusuf', name: 'Yusuf Karim', initials: 'YK', role: 'contributor', title: 'Delivery engineer', color: '#2563eb', workstreamIds: ['ws-assistant', 'ws-data'], canApproveReports: false },
    { id: 'dev-maya', name: 'Maya Patel', initials: 'MP', role: 'contributor', title: 'AI engineer', color: '#9333ea', workstreamIds: ['ws-assistant', 'ws-evaluation'], canApproveReports: false },
    { id: 'data-noor', name: 'Noor Aziz', initials: 'NA', role: 'contributor', title: 'Data and evaluation analyst', color: '#059669', workstreamIds: ['ws-data', 'ws-evaluation'], canApproveReports: false },
    { id: 'qa-ellie', name: 'Ellie Morgan', initials: 'EM', role: 'contributor', title: 'Quality and release engineer', color: '#d97706', workstreamIds: allStreams, canApproveReports: false },
    { id: 'admin-jules', name: 'Jules Park', initials: 'JP', role: 'admin', title: 'Demo administrator', color: '#64748b', workstreamIds: allStreams, canApproveReports: false },
  ];
  const workstreams: HubState['workstreams'] = [
    { ...v('ws-assistant', -5, 4), name: 'Knowledge assistant', shortName: 'Assistant', description: 'A grounded, accessible assistant for service operations teams.', leadId: 'lead-leila', health: 'amber', statusNote: 'Answer feedback is awaiting client acceptance. The citation navigation fix needs another UAT pass.', clientSummary: 'Answer feedback is ready for client review. Citation navigation remains in validation.', color: '#7c3aed' },
    { ...v('ws-data', -1, 5), name: 'Data foundation', shortName: 'Data', description: 'Reliable source ingestion, trustworthy definitions, and usable data quality signals.', leadId: 'lead-arjun', health: 'red', statusNote: 'The landing-zone access request is overdue; finance ingestion cannot reach UAT until the service account is enabled.', clientSummary: 'Finance ingestion is dependent on source-system access. The revised forecast is under review.', color: '#0891b2' },
    { ...v('ws-evaluation', -144, 2), name: 'Evaluation & assurance', shortName: 'Evaluation', description: 'Repeatable quality evaluation, representative test cases, and evidence for release decisions.', leadId: 'lead-sara', health: 'green', statusNote: 'Benchmark design was accepted last week. This period has not yet been confirmed.', clientSummary: 'Benchmark design is complete; evaluation results and acceptance thresholds are the next focus.', color: '#ea580c' },
  ];
  const deliverables: HubState['deliverables'] = [
    { ...v('del-assistant-experience'), title: 'Assistant experience improvements', workstreamId: 'ws-assistant', ownerId: 'lead-leila', description: 'Accessible interaction, clear citations, and useful answer feedback.' },
    { ...v('del-assistant-release'), title: 'Assistant release readiness', workstreamId: 'ws-assistant', ownerId: 'lead-leila', description: 'Session resilience, release evidence, and client acceptance.' },
    { ...v('del-data-pipeline'), title: 'Finance ingestion pipeline', workstreamId: 'ws-data', ownerId: 'lead-arjun', description: 'Incremental source ingestion with repeatable validation and recovery.' },
    { ...v('del-data-quality'), title: 'Data quality baseline', workstreamId: 'ws-data', ownerId: 'lead-arjun', description: 'Agreed data definitions, reference samples, and monitored quality rules.' },
    { ...v('del-evaluation-suite'), title: 'Evaluation benchmark suite', workstreamId: 'ws-evaluation', ownerId: 'lead-sara', description: 'Representative test data, reproducible runs, and useful failure analysis.' },
    { ...v('del-evaluation-governance'), title: 'Release assurance criteria', workstreamId: 'ws-evaluation', ownerId: 'lead-sara', description: 'Agreed quality thresholds and a documented review approach.' },
  ];
  const milestones: HubState['milestones'] = [
    { ...v('ms-assistant-pilot', -5, 3), title: 'Assistant pilot accepted', workstreamIds: ['ws-assistant', 'ws-evaluation'], deliverableIds: ['del-assistant-experience', 'del-evaluation-suite'], ownerId: 'lead-leila', baselineDate: date(4), forecastDate: date(7), status: 'at_risk', notes: 'Citation navigation rework and the final client acceptance session are outstanding.' },
    { ...v('ms-finance-ready', -1, 4), title: 'Finance ingestion ready for UAT', workstreamIds: ['ws-data'], deliverableIds: ['del-data-pipeline'], ownerId: 'lead-arjun', baselineDate: date(-1), forecastDate: date(5), status: 'at_risk', notes: 'Forecast assumes source-system access is enabled within two working days.' },
    { ...v('ms-quality-baseline', -24), title: 'Data quality baseline signed off', workstreamIds: ['ws-data'], deliverableIds: ['del-data-quality'], ownerId: 'lead-arjun', baselineDate: date(6), forecastDate: date(6), status: 'planned', notes: 'Null-rate and duplicate thresholds are ready for review.' },
    { ...v('ms-benchmark-design', -48, 2), title: 'Benchmark design accepted', workstreamIds: ['ws-evaluation'], deliverableIds: ['del-evaluation-governance'], ownerId: 'lead-sara', baselineDate: date(-3), forecastDate: date(-3), actualDate: date(-3), status: 'complete', notes: 'Review covered case selection, scoring, and ownership of disputed labels.' },
    { ...v('ms-release-review', -48), title: 'Integrated release assurance review', workstreamIds: allStreams, deliverableIds: ['del-assistant-release', 'del-data-pipeline', 'del-evaluation-suite'], ownerId: 'exec-omar', baselineDate: date(12), forecastDate: date(12), status: 'planned', notes: 'Bring release evidence, open dependencies, and proposed client acceptance criteria.' },
  ];

  type SeedItem = Pick<WorkItem, 'id' | 'title' | 'description' | 'acceptanceCriteria' | 'workstreamId' | 'stage' | 'currentOwnerId'> & Partial<WorkItem> & { dueIn?: number };
  const makeItem = ({ dueIn = 3, ...spec }: SeedItem): WorkItem => {
    const stream = workstreams.find(w => w.id === spec.workstreamId)!;
    const general = spec.kind === 'general';
    return {
      ...v(spec.id, spec.workstreamId === 'ws-data' ? -1 : -8, 2),
      kind: general ? 'general' : 'software', category: general ? 'action' : 'feature', priority: 'Medium',
      ownerId: stream.leadId, deliverableId: deliverables.find(d => d.workstreamId === stream.id)!.id,
      baselineDate: date(dueIn), dueDate: date(dueIn), evidenceLinks: [],
      blocked: false, blockReason: '', nextAction: general ? 'Complete the next review step and attach the outcome.' : 'Complete the current stage and assign the next delivery owner.',
      clientSummary: spec.title, clientVisible: true, cycle: 1, createdAt: at(-21 * 24), tags: [],
      ...spec,
      ...(spec.stage === 'Closed' ? { closedAt: spec.closedAt ?? at(-48) } : {}),
    };
  };
  const items: WorkItem[] = [
    makeItem({ id: 'work-assistant-01', workstreamId: 'ws-assistant', title: 'Keep citation links in the current answer', description: 'Selecting a second citation loses the first answer context after a browser back action.', acceptanceCriteria: 'Every citation opens its matching source; returning preserves the answer and keyboard focus.', stage: 'UAT', currentOwnerId: 'qa-ellie', category: 'bug', priority: 'High', dueIn: -1, nextAction: 'Retest browser-back navigation after the patch and record the result.', evidenceLinks: [evidence('citation-navigation-uat')], tags: ['accessibility', 'retest'] }),
    makeItem({ id: 'work-assistant-02', workstreamId: 'ws-assistant', title: 'Capture answer feedback with an optional reason', description: 'Let a service agent flag an unhelpful answer without leaving the conversation.', acceptanceCriteria: 'Positive and negative feedback persist once; the reason is optional; confirmation is announced to assistive technology.', stage: 'Awaiting client acceptance', currentOwnerId: 'lead-leila', dueIn: 1, nextAction: 'Record the client response and acceptance evidence from the pilot review.', evidenceLinks: [evidence('feedback-production-check')], tags: ['client-review'] }),
    makeItem({ id: 'work-assistant-03', workstreamId: 'ws-assistant', title: 'Use the agreed font across answer cards', description: 'Bring answer text, citation labels, and empty states into the approved typography scale.', acceptanceCriteria: 'All three components match the design reference at desktop and narrow widths; no clipped text.', stage: 'Development', currentOwnerId: 'dev-yusuf', category: 'bug', dueIn: 2, nextAction: 'Finish the narrow-screen regression and request UAT.', tags: ['ui'] }),
    makeItem({ id: 'work-assistant-04', workstreamId: 'ws-assistant', title: 'Handle a session timeout without losing the question', description: 'Preserve the typed question when authentication expires during a conversation.', acceptanceCriteria: 'The user can sign in again and recover their draft; no previous user conversation is displayed.', stage: 'Production verification', currentOwnerId: 'dev-maya', deliverableId: 'del-assistant-release', priority: 'High', dueIn: 0, evidenceLinks: [evidence('session-release-notes')], nextAction: 'Verify the timeout behavior in production, then request client acceptance.' }),
    makeItem({ id: 'work-assistant-05', workstreamId: 'ws-assistant', title: 'Confirm the pilot support coverage', description: 'INTERNAL-ONLY-COMMERCIAL-NOTE: fictional reserve estimate and staffing discussion; keep this internal. Confirm named support contacts for pilot hours.', acceptanceCriteria: 'Every pilot window has a primary contact and an escalation contact.', kind: 'general', category: 'action', stage: 'In progress', currentOwnerId: 'lead-leila', deliverableId: 'del-assistant-release', clientVisible: false, clientSummary: '', dueIn: 2, tags: ['internal'] }),
    makeItem({ id: 'work-assistant-06', workstreamId: 'ws-assistant', title: 'Explain when an answer has insufficient evidence', description: 'Replace a generic failure response with a concise explanation and a suggested next step.', acceptanceCriteria: 'Unanswerable questions receive no fabricated answer and show the approved help route.', stage: 'Ready for production', currentOwnerId: 'dev-yusuf', dueIn: 1, evidenceLinks: [evidence('insufficient-evidence-uat')], nextAction: 'Deploy the approved build in the next release window.' }),
    makeItem({ id: 'work-assistant-07', workstreamId: 'ws-assistant', title: 'Improve the source freshness label', description: 'The client rejected the original date label because it implied a live source refresh. Rework the same item through the complete delivery cycle.', acceptanceCriteria: 'Labels distinguish document publication from last ingestion and use wording accepted by the client.', stage: 'Development', currentOwnerId: 'dev-maya', category: 'bug', cycle: 2, priority: 'High', dueIn: 3, baselineDate: date(-4), nextAction: 'Implement the clarified label and repeat UAT, deployment, verification, and client acceptance.', tags: ['client-rejected', 'rework'], evidenceLinks: [evidence('freshness-client-response')] }),
    makeItem({ id: 'work-assistant-08', workstreamId: 'ws-assistant', title: 'Publish the pilot quick-start guide', description: 'A one-page guide explains supported questions, evidence links, and how to report problems.', acceptanceCriteria: 'The workstream lead has accepted the guide and the published link is available to pilot participants.', kind: 'general', category: 'action', stage: 'Closed', currentOwnerId: 'lead-leila', dueIn: -2, closedAt: at(-36), evidenceLinks: [evidence('pilot-quick-start')], nextAction: 'Monitor questions raised by pilot participants.' }),
    makeItem({ id: 'work-assistant-09', workstreamId: 'ws-assistant', title: 'Restore focus after closing the source panel', description: 'Keyboard users should return to the citation they opened after closing the source panel.', acceptanceCriteria: 'Escape closes the panel and returns keyboard focus to the originating citation.', stage: 'Closed', currentOwnerId: 'lead-leila', category: 'bug', dueIn: -3, closedAt: at(-60), evidenceLinks: [evidence('source-focus-client-acceptance')], nextAction: 'No further action; client acceptance recorded.' }),
    makeItem({ id: 'work-assistant-10', workstreamId: 'ws-assistant', title: 'Add a concise conversation title', description: 'Allow pilot agents to identify earlier conversations without opening each one.', acceptanceCriteria: 'The title is editable, persists after refresh, and does not include sensitive answer content.', stage: 'Backlog', currentOwnerId: 'dev-yusuf', dueIn: 9, priority: 'Low', nextAction: 'Confirm the interaction details before starting development.' }),
    makeItem({ id: 'work-data-01', workstreamId: 'ws-data', title: 'Enable finance source access for the service account', description: 'The approved service account still lacks read access to the finance landing zone.', acceptanceCriteria: 'The service account can read the agreed sample path with least-privilege permissions; access evidence is captured.', kind: 'general', category: 'action', stage: 'In progress', currentOwnerId: 'lead-arjun', priority: 'Critical', dueIn: -3, blocked: true, blockReason: 'Awaiting the client platform team to complete the access request.', blockedSince: at(-5 * 24), nextAction: 'Obtain an access completion time from the platform owner today.', evidenceLinks: [evidence('finance-access-request')], tags: ['access', 'client-dependency'] }),
    makeItem({ id: 'work-data-02', workstreamId: 'ws-data', title: 'Load incremental finance extracts without duplicates', description: 'Process only new extract partitions and safely handle a replay of the same batch.', acceptanceCriteria: 'Reprocessing an extract produces identical row counts and no duplicate business keys.', stage: 'Development', currentOwnerId: 'dev-yusuf', priority: 'High', dueIn: 2, baselineDate: date(-1), blocked: true, blockReason: 'Integration testing needs the finance service account access.', blockedSince: at(-72), nextAction: 'Continue fixture-based checks; run source validation when access is available.' }),
    makeItem({ id: 'work-data-03', workstreamId: 'ws-data', title: 'Agree the customer identifier mapping', description: 'Document how legacy customer codes map to the canonical identifier and resolve ambiguous examples.', acceptanceCriteria: 'The data owner has reviewed every ambiguous mapping and approved the mapping document.', kind: 'general', category: 'data', stage: 'Review', currentOwnerId: 'lead-arjun', deliverableId: 'del-data-quality', dueIn: 1, nextAction: 'Resolve the three ambiguous examples with the data owner.' }),
    makeItem({ id: 'work-data-04', workstreamId: 'ws-data', title: 'Raise an alert when freshness exceeds the threshold', description: 'Surface the last successful ingestion time and alert when a scheduled source becomes stale.', acceptanceCriteria: 'A deliberately delayed fixture triggers one alert with source name and last success time.', stage: 'UAT', currentOwnerId: 'data-noor', dueIn: 2, evidenceLinks: [evidence('freshness-monitor-test-plan')], nextAction: 'Run delayed-source and recovery scenarios.' }),
    makeItem({ id: 'work-data-05', workstreamId: 'ws-data', title: 'Baseline missing-value rates for priority fields', description: 'Profile customer and transaction samples to establish the starting null-rate distribution.', acceptanceCriteria: 'The profile lists sample dates, record counts, field-level null rates, and the agreed exceptions.', kind: 'general', category: 'data', stage: 'Closed', currentOwnerId: 'lead-arjun', deliverableId: 'del-data-quality', dueIn: -2, closedAt: at(-30), evidenceLinks: [evidence('null-rate-baseline')], nextAction: 'Use the accepted baseline to set monitoring thresholds.' }),
    makeItem({ id: 'work-data-06', workstreamId: 'ws-data', title: 'Recover cleanly from a partial ingestion failure', description: 'A failed partition should be retryable without rebuilding the entire daily load.', acceptanceCriteria: 'A forced mid-batch failure leaves a recoverable checkpoint; replay produces the expected total.', stage: 'Backlog', currentOwnerId: 'dev-yusuf', priority: 'High', dueIn: 8, nextAction: 'Agree retry boundaries and checkpoint evidence before development.' }),
    makeItem({ id: 'work-data-07', workstreamId: 'ws-data', title: 'Document source retention and sample handling', description: 'Record the approved retention expectations and disposal responsibilities for demo-independent project data.', acceptanceCriteria: 'Data owners have reviewed retention periods, sample locations, and deletion responsibilities.', kind: 'general', category: 'research', stage: 'Review', currentOwnerId: 'lead-arjun', deliverableId: 'del-data-quality', dueIn: 4, nextAction: 'Capture the data-owner review outcome.' }),
    makeItem({ id: 'work-data-08', workstreamId: 'ws-data', title: 'Correct timezone conversion in transaction dates', description: 'Late-night source transactions were assigned to the wrong reporting date after conversion.', acceptanceCriteria: 'Boundary fixtures preserve the agreed business date across UTC and Dubai time.', stage: 'Awaiting client acceptance', currentOwnerId: 'lead-arjun', category: 'bug', dueIn: 0, evidenceLinks: [evidence('transaction-date-production-check')], nextAction: 'Record the client review of the corrected boundary examples.' }),
    makeItem({ id: 'work-data-09', workstreamId: 'ws-data', title: 'Publish the agreed source-to-target dictionary', description: 'Give delivery and evaluation teams a consistent reference for field meaning, ownership, and transformations.', acceptanceCriteria: 'Every priority field has an owner, definition, source, target, and documented transformation.', kind: 'general', category: 'data', stage: 'In progress', currentOwnerId: 'data-noor', deliverableId: 'del-data-quality', dueIn: 5, nextAction: 'Complete the finance fields and send the dictionary for review.' }),
    makeItem({ id: 'work-data-10', workstreamId: 'ws-data', title: 'Expose ingestion run identifiers in monitoring', description: 'Use the same run identifier in load logs and monitoring so failures can be traced quickly.', acceptanceCriteria: 'A run identifier can be followed from the monitoring entry to all associated batch logs.', stage: 'Ready for production', currentOwnerId: 'dev-yusuf', dueIn: 1, evidenceLinks: [evidence('run-id-uat')], nextAction: 'Include the verified change in the next pipeline release.' }),
    makeItem({ id: 'work-evaluation-01', workstreamId: 'ws-evaluation', title: 'Accept the benchmark sampling approach', description: 'Define how common, difficult, and unanswerable questions are represented in the first evaluation set.', acceptanceCriteria: 'The lead has accepted the sampling rationale, category coverage, and review procedure.', kind: 'general', category: 'evaluation', stage: 'Closed', currentOwnerId: 'lead-sara', deliverableId: 'del-evaluation-governance', dueIn: -3, closedAt: at(-72), evidenceLinks: [evidence('benchmark-design-review')], nextAction: 'Apply the approved approach to the next sample.' }),
    makeItem({ id: 'work-evaluation-02', workstreamId: 'ws-evaluation', title: 'Resolve disputed expected-answer labels', description: 'Two subject-matter reviewers disagree on the accepted interpretation of eight test questions.', acceptanceCriteria: 'Every disputed case has a recorded resolution and a named subject-matter reviewer.', kind: 'general', category: 'evaluation', stage: 'Review', currentOwnerId: 'lead-sara', priority: 'High', dueIn: -1, blocked: true, blockReason: 'The subject-matter review slot has not been confirmed.', blockedSince: at(-48), nextAction: 'Confirm a review slot and circulate the eight disputed examples.' }),
    makeItem({ id: 'work-evaluation-03', workstreamId: 'ws-evaluation', title: 'Run the grounded-answer regression set', description: 'Evaluate the current assistant build against representative questions and inspect unsupported claims.', acceptanceCriteria: 'The run records build, dataset version, scoring configuration, aggregate results, and reviewed failures.', kind: 'general', category: 'evaluation', stage: 'In progress', currentOwnerId: 'data-noor', dueIn: 3, nextAction: 'Finish the run and group failures by root cause.', tags: ['quality'] }),
    makeItem({ id: 'work-evaluation-04', workstreamId: 'ws-evaluation', title: 'Make evaluation runs reproducible', description: 'Persist dataset version and evaluation settings alongside each run identifier.', acceptanceCriteria: 'A teammate can rerun the same configuration and identify any intentionally variable inputs.', stage: 'UAT', currentOwnerId: 'qa-ellie', dueIn: 2, evidenceLinks: [evidence('evaluation-reproducibility-plan')], nextAction: 'Reproduce a run from its recorded configuration.' }),
    makeItem({ id: 'work-evaluation-05', workstreamId: 'ws-evaluation', title: 'Agree the pilot acceptance thresholds', description: 'Turn the benchmark findings into explicit release criteria and identify any accepted exceptions.', acceptanceCriteria: 'Thresholds state the metric, measurement set, minimum result, and named decision owner.', kind: 'general', category: 'evaluation', stage: 'Review', currentOwnerId: 'lead-sara', deliverableId: 'del-evaluation-governance', priority: 'High', dueIn: 2, nextAction: 'Present the proposed thresholds and document the decision.' }),
    makeItem({ id: 'work-evaluation-06', workstreamId: 'ws-evaluation', title: 'Investigate retrieval failures on short questions', description: 'Classify whether missing evidence comes from query ambiguity, source coverage, or retrieval ranking.', acceptanceCriteria: 'The analysis uses a reproducible sample and recommends an owner and next step for each failure class.', kind: 'general', category: 'research', stage: 'In progress', currentOwnerId: 'dev-maya', dueIn: 5, nextAction: 'Complete failure classification and review recommendations.' }),
    makeItem({ id: 'work-evaluation-07', workstreamId: 'ws-evaluation', title: 'Export per-case evaluation evidence', description: 'Let reviewers inspect the input, retrieved sources, response, and scoring notes for each failed case.', acceptanceCriteria: 'The export contains the selected run only and preserves case IDs and evidence links.', stage: 'Development', currentOwnerId: 'dev-maya', dueIn: 4, nextAction: 'Implement the export and test a run containing mixed pass/fail cases.' }),
    makeItem({ id: 'work-evaluation-08', workstreamId: 'ws-evaluation', title: 'Review prompt-injection evaluation coverage', description: 'Assess representative malicious document instructions and confirm the expected safe behavior.', acceptanceCriteria: 'The review records covered scenarios, expected behavior, known gaps, and ownership for follow-up.', kind: 'general', category: 'research', stage: 'Closed', currentOwnerId: 'lead-sara', deliverableId: 'del-evaluation-governance', dueIn: -4, closedAt: at(-84), evidenceLinks: [evidence('injection-coverage-review')], nextAction: 'Carry the documented gaps into the next evaluation cycle.' }),
    makeItem({ id: 'work-evaluation-09', workstreamId: 'ws-evaluation', title: 'Summarize quality findings for the pilot review', description: 'Prepare a short, evidence-backed explanation of release confidence and remaining limitations.', acceptanceCriteria: 'Every numerical claim identifies its evaluation run; limitations and open dependencies are explicit.', kind: 'general', category: 'evaluation', stage: 'Backlog', currentOwnerId: 'lead-sara', deliverableId: 'del-evaluation-governance', dueIn: 6, nextAction: 'Draft the summary after the regression run and threshold decision.' }),
    makeItem({ id: 'work-evaluation-10', workstreamId: 'ws-evaluation', title: 'Correct the evaluation chart legend', description: 'The chart legend reverses the labels for unsupported and incomplete answers.', acceptanceCriteria: 'Legend labels and colors match the documented failure categories on every chart.', stage: 'Production verification', currentOwnerId: 'qa-ellie', category: 'bug', dueIn: 1, evidenceLinks: [evidence('chart-legend-release')], nextAction: 'Verify the chart labels against the known reference run.' }),
  ];

  const tests: HubState['tests'] = [
    { id: 'test-citation-fail', itemId: 'work-assistant-01', cycle: 1, stage: 'UAT', result: 'fail', blocking: true, notes: 'Browser back returns to the conversation list instead of the selected answer.', evidence: evidence('citation-navigation-uat'), authorId: 'qa-ellie', createdAt: at(-28) },
    { id: 'test-feedback-uat', itemId: 'work-assistant-02', cycle: 1, stage: 'UAT', result: 'pass', blocking: false, notes: 'Feedback persists once; optional reason and keyboard announcement verified.', evidence: evidence('feedback-uat'), authorId: 'dev-maya', createdAt: at(-96) },
    { id: 'test-feedback-production', itemId: 'work-assistant-02', cycle: 1, stage: 'Production verification', result: 'pass', blocking: false, notes: 'Verified the deployed build with the pilot account and confirmed feedback persistence.', evidence: evidence('feedback-production-check'), authorId: 'qa-ellie', createdAt: at(-30) },
    { id: 'test-freshness-previous-uat', itemId: 'work-assistant-07', cycle: 1, stage: 'UAT', result: 'pass', blocking: false, notes: 'The original label met the initial wording criteria.', evidence: evidence('freshness-cycle-one-uat'), authorId: 'qa-ellie', createdAt: at(-168) },
    { id: 'test-freshness-previous-production', itemId: 'work-assistant-07', cycle: 1, stage: 'Production verification', result: 'pass', blocking: false, notes: 'The original build was verified before the client requested a wording change.', evidence: evidence('freshness-cycle-one-production'), authorId: 'dev-yusuf', createdAt: at(-120) },
    { id: 'test-empty-answer-uat', itemId: 'work-assistant-06', cycle: 1, stage: 'UAT', result: 'pass', blocking: false, notes: 'All unanswerable fixtures show the approved message and help route.', evidence: evidence('insufficient-evidence-uat'), authorId: 'qa-ellie', createdAt: at(-24) },
    { id: 'test-focus-uat', itemId: 'work-assistant-09', cycle: 1, stage: 'UAT', result: 'pass', blocking: false, notes: 'Keyboard focus returns to the triggering citation.', evidence: evidence('source-focus-uat'), authorId: 'dev-maya', createdAt: at(-144) },
    { id: 'test-focus-production', itemId: 'work-assistant-09', cycle: 1, stage: 'Production verification', result: 'pass', blocking: false, notes: 'Verified keyboard and screen-reader behavior in the released build.', evidence: evidence('source-focus-production'), authorId: 'qa-ellie', createdAt: at(-96) },
    { id: 'test-dates-uat', itemId: 'work-data-08', cycle: 1, stage: 'UAT', result: 'pass', blocking: false, notes: 'Boundary fixtures preserve the correct Dubai reporting date.', evidence: evidence('transaction-date-uat'), authorId: 'data-noor', createdAt: at(-72) },
    { id: 'test-dates-production', itemId: 'work-data-08', cycle: 1, stage: 'Production verification', result: 'pass', blocking: false, notes: 'Production output matches the agreed boundary examples.', evidence: evidence('transaction-date-production-check'), authorId: 'qa-ellie', createdAt: at(-24) },
    { id: 'test-run-id-uat', itemId: 'work-data-10', cycle: 1, stage: 'UAT', result: 'pass', blocking: false, notes: 'The run ID joins monitoring and batch logs for success and failure scenarios.', evidence: evidence('run-id-uat'), authorId: 'data-noor', createdAt: at(-26) },
    { id: 'test-timeout-uat', itemId: 'work-assistant-04', cycle: 1, stage: 'UAT', result: 'pass', blocking: false, notes: 'A timed-out session preserves the draft after reauthentication.', evidence: evidence('session-timeout-uat'), authorId: 'qa-ellie', createdAt: at(-48) },
    { id: 'test-legend-uat', itemId: 'work-evaluation-10', cycle: 1, stage: 'UAT', result: 'pass', blocking: false, notes: 'The legend matches the reference fixture and documented categories.', evidence: evidence('chart-legend-uat'), authorId: 'data-noor', createdAt: at(-48) },
    { id: 'test-guide-review', itemId: 'work-assistant-08', cycle: 1, stage: 'Review', result: 'pass', blocking: false, notes: 'Quick-start guide accepted against the review checklist.', evidence: evidence('pilot-quick-start'), authorId: 'lead-leila', createdAt: at(-37) },
    { id: 'test-profile-review', itemId: 'work-data-05', cycle: 1, stage: 'Review', result: 'pass', blocking: false, notes: 'Record counts, sampling dates, null rates, and exceptions are documented.', evidence: evidence('null-rate-baseline'), authorId: 'lead-arjun', createdAt: at(-31) },
    { id: 'test-benchmark-review', itemId: 'work-evaluation-01', cycle: 1, stage: 'Review', result: 'pass', blocking: false, notes: 'Sampling rationale, category coverage, and review procedure accepted.', evidence: evidence('benchmark-design-review'), authorId: 'lead-sara', createdAt: at(-73) },
    { id: 'test-coverage-review', itemId: 'work-evaluation-08', cycle: 1, stage: 'Review', result: 'pass', blocking: false, notes: 'Coverage gaps and follow-up owners are explicit in the accepted review.', evidence: evidence('injection-coverage-review'), authorId: 'lead-sara', createdAt: at(-85) },
  ];
  const registerBase = { version: 1, updatedAt: at(-8), clientVisible: true, relatedItemIds: [] as string[], milestoneIds: [] as string[], priority: 'Medium' as const, probability: 'Medium' as const, status: 'open' as const };
  const registers: HubState['registers'] = [
    { ...registerBase, id: 'reg-finance-access', type: 'dependency', title: 'Finance source access is overdue', detail: 'Read permissions for the service account are still pending with the client platform team.', clientSummary: 'Finance ingestion requires completion of the source access request.', workstreamId: 'ws-data', relatedItemIds: ['work-data-01', 'work-data-02'], milestoneIds: ['ms-finance-ready'], ownerId: 'lead-arjun', dueDate: date(-3), priority: 'Critical', status: 'escalated', mitigation: 'Continue fixture-based pipeline checks while access is arranged.', nextAction: 'Confirm the platform owner and obtain a dated completion commitment.', impact: 'Live-source validation and the UAT milestone cannot complete.' },
    { ...registerBase, id: 'reg-citation-failure', type: 'issue', title: 'Citation navigation failed UAT', detail: 'The browser-back scenario lost answer context during the second UAT pass.', clientSummary: 'Citation navigation is undergoing a further validation pass.', workstreamId: 'ws-assistant', relatedItemIds: ['work-assistant-01'], milestoneIds: ['ms-assistant-pilot'], ownerId: 'lead-leila', dueDate: date(1), priority: 'High', mitigation: 'Apply the navigation fix and rerun the full source-panel regression.', nextAction: 'Record the retest outcome and confirm the release forecast.', impact: 'The assistant pilot could slip if the retest does not pass.' },
    { ...registerBase, id: 'reg-reviewer-availability', type: 'risk', title: 'Subject-matter reviewers may miss the label review', detail: 'The review slot for disputed expected answers is not yet confirmed.', clientSummary: 'A subject-matter review is required to finalize the expected-answer set.', workstreamId: 'ws-evaluation', relatedItemIds: ['work-evaluation-02'], milestoneIds: ['ms-assistant-pilot', 'ms-release-review'], ownerId: 'lead-sara', dueDate: date(1), priority: 'High', probability: 'High', mitigation: 'Circulate the eight cases in advance and offer two short review slots.', nextAction: 'Get confirmation of a named reviewer and review time.', impact: 'The final regression run may use provisional labels.' },
    { ...registerBase, id: 'reg-quality-thresholds', type: 'decision', title: 'Agree the pilot quality thresholds', detail: 'The release review needs an agreed threshold and exception owner for each measured quality dimension.', clientSummary: 'Approval of the proposed pilot quality thresholds is requested.', workstreamId: 'ws-evaluation', relatedItemIds: ['work-evaluation-05'], milestoneIds: ['ms-release-review'], ownerId: 'lead-sara', dueDate: date(2), priority: 'High', mitigation: 'Prepare the proposed thresholds with examples and tradeoffs.', nextAction: 'Bring the decision to the pilot review and record the outcome.', impact: 'Release confidence cannot be assessed consistently until criteria are agreed.' },
    { ...registerBase, id: 'reg-source-window', type: 'assumption', title: 'Finance extracts arrive before the morning load', detail: 'The initial design assumes the previous business day extract is available before the scheduled load.', clientSummary: 'The source extract availability window is being confirmed.', workstreamId: 'ws-data', relatedItemIds: ['work-data-02', 'work-data-04'], ownerId: 'lead-arjun', dueDate: date(3), status: 'monitoring', mitigation: 'Support late-file detection and retain the last successful run timestamp.', nextAction: 'Validate the assumed window with the source-system owner.', impact: 'An incorrect assumption affects freshness targets and monitoring thresholds.' },
    { ...registerBase, id: 'reg-client-review', type: 'dependency', title: 'Client review of answer feedback is needed', detail: 'Internal production verification passed; the acceptance session is the remaining completion step.', clientSummary: 'Answer feedback is awaiting client acceptance following internal verification.', workstreamId: 'ws-assistant', relatedItemIds: ['work-assistant-02'], milestoneIds: ['ms-assistant-pilot'], ownerId: 'lead-leila', dueDate: date(1), mitigation: 'Share the acceptance checklist and production evidence before the session.', nextAction: 'Record the client acceptance or rejection with supporting evidence.', impact: 'The item must remain open until the client response is recorded.' },
    { ...registerBase, id: 'reg-label-decision', type: 'decision', title: 'Use explicit source publication and ingestion labels', detail: 'The client rejected the original generic freshness label; the same work item is in rework cycle two.', clientSummary: 'The revised source-date wording distinguishes publication and ingestion dates.', workstreamId: 'ws-assistant', relatedItemIds: ['work-assistant-07'], ownerId: 'lead-leila', dueDate: date(-1), status: 'resolved', mitigation: 'Repeat the full delivery and acceptance cycle using the clarified criteria.', nextAction: 'Implement the recorded wording decision in the linked item.', impact: 'Avoids implying that a document has been updated when only ingestion has occurred.' },
    { ...registerBase, id: 'reg-support-coverage', type: 'risk', title: 'Pilot support coverage still needs confirmation', detail: 'INTERNAL-ONLY-COMMERCIAL-NOTE: fictional staffing reserve and commercial discussion. Confirm coverage without including these notes in client materials.', clientSummary: '', clientVisible: false, workstreamId: 'ws-assistant', relatedItemIds: ['work-assistant-05'], ownerId: 'lead-leila', dueDate: date(2), probability: 'Low', mitigation: 'Confirm named contacts and escalation routes for the agreed pilot hours.', nextAction: 'Complete the internal support roster.', impact: 'Unclear coverage could delay the response to pilot questions.' },
    { ...registerBase, id: 'reg-identifier-review', type: 'dependency', title: 'Data owner review of ambiguous customer mappings', detail: 'Three legacy customer identifiers still need an authoritative mapping decision.', clientSummary: 'Data-owner input is needed for three customer identifier mappings.', workstreamId: 'ws-data', relatedItemIds: ['work-data-03'], milestoneIds: ['ms-quality-baseline'], ownerId: 'lead-arjun', dueDate: date(1), mitigation: 'Keep unresolved examples out of accepted reference mappings.', nextAction: 'Obtain the data owner review and record the approved mappings.', impact: 'The canonical mapping cannot be accepted while the three examples remain unresolved.' },
  ];
  const meetings: HubState['meetings'] = [
    { ...v('meeting-daily', -5, 2), title: 'Daily delivery sync', heldAt: at(-6), notes: 'Finance access remains the priority escalation. Arjun will obtain a dated commitment. Ellie is retesting citation navigation. Leila will record the client response on answer feedback. Use the linked records for ownership and due dates.', linkedItemIds: ['work-data-01', 'work-assistant-01', 'work-assistant-02'], linkedRegisterIds: ['reg-finance-access', 'reg-client-review'] },
    { ...v('meeting-quality-review', -48), title: 'Benchmark and quality review', heldAt: at(-50), notes: 'Benchmark design was accepted. Sara will obtain reviewer availability for the eight disputed labels. The pilot threshold decision remains open; the proposed criteria need explicit approval.', linkedItemIds: ['work-evaluation-01', 'work-evaluation-02', 'work-evaluation-05'], linkedRegisterIds: ['reg-reviewer-availability', 'reg-quality-thresholds'] },
    { ...v('meeting-client-feedback', -32), title: 'Pilot feedback follow-up', heldAt: at(-34), notes: 'Internal record of the client response: the source freshness label was rejected because it implied live content refresh. Rework stays on the same item. Production verification alone does not close the feedback item.', linkedItemIds: ['work-assistant-07', 'work-assistant-02'], linkedRegisterIds: ['reg-label-decision', 'reg-client-review'] },
  ];
  const submissions: HubState['submissions'] = [
    { ...v('submission-assistant-current', -3, 2), workstreamId: 'ws-assistant', periodEnd: periodEnd(0), completed: 'Pilot quick-start guide accepted. Source-panel focus fix has client acceptance.', next: 'Retest citation navigation; record client acceptance of answer feedback; complete source-label rework.', changes: 'Pilot forecast moved by three days to allow rework and acceptance.', blockers: 'Client acceptance session is outstanding for answer feedback.', health: 'amber', confirmedBy: 'lead-leila', confirmedAt: at(-3), sourceUpdatedAt: at(-5) },
    { ...v('submission-data-current', -26), workstreamId: 'ws-data', periodEnd: periodEnd(0), completed: 'Missing-value baseline accepted.', next: 'Finish finance ingestion checks and customer mapping review.', changes: 'Finance source access remains pending.', blockers: 'Source access and three customer mapping decisions are outstanding.', health: 'amber', confirmedBy: 'lead-arjun', confirmedAt: at(-26), sourceUpdatedAt: at(-28) },
  ];

  const historicalReport = (index: number): Report => {
    // A seed made just after cutoff must not manufacture a future approval.
    const skipUnpublishedCutoff = new Date(cutoff(-1)).getTime() + 30 * 60_000 >= now.getTime() ? 1 : 0;
    const offset = -index - skipUnpublishedCutoff;
    const asOf = cutoff(offset);
    const end = periodEnd(offset);
    const start = new Date(new Date(asOf).getTime() - 7 * day).toISOString().slice(0, 10);
    const approvedAt = new Date(new Date(asOf).getTime() + 30 * 60_000).toISOString();
    return {
      id: `report-client-${index}`, version: 2, updatedAt: approvedAt,
      title: `Client weekly · ${end}`, audience: 'client', periodStart: start, periodEnd: end,
      asOf, status: 'approved', createdBy: 'pmo-nadia', createdAt: asOf, approvedBy: 'exec-omar', approvedAt,
      sourceVersions: { 'workstreams:ws-assistant': index === 1 ? 3 : 2, 'workstreams:ws-data': index === 1 ? 3 : 2, 'workstreams:ws-evaluation': index === 1 ? 2 : 1 },
      body: index === 1 ? {
        summary: 'The assistant, data, and evaluation workstreams progressed their agreed phase-two foundations. Source access and review availability remain the main dependencies.',
        highlights: ['Assistant interaction criteria were agreed.', 'The priority source-field inventory was reviewed.', 'Benchmark categories and review ownership were agreed.'],
        nextWeek: ['Validate the assistant improvements through the delivery cycle.', 'Complete source access and continue ingestion validation.', 'Resolve expected-answer labels and prepare pilot thresholds.'],
        attention: ['Source-system access is required for live finance validation.', 'Subject-matter reviewer availability needs confirmation.'],
        workstreams: [
          { name: 'Knowledge assistant', health: 'amber', completed: ['Interaction criteria agreed.'], next: ['Complete UAT for the first improvements.'], attention: ['Schedule client acceptance after verification.'], confirmed: true },
          { name: 'Data foundation', health: 'amber', completed: ['Priority source-field inventory reviewed.'], next: ['Validate the first finance extract.'], attention: ['Source access pending.'], confirmed: true },
          { name: 'Evaluation & assurance', health: 'green', completed: ['Benchmark categories agreed.'], next: ['Review expected-answer labels.'], attention: ['Confirm reviewer availability.'], confirmed: true },
        ],
        milestones: [{ title: 'Assistant pilot accepted', forecastDate: date(4), status: 'planned' }, { title: 'Finance ingestion ready for UAT', forecastDate: date(-1), status: 'at_risk' }],
      } : {
        summary: 'Phase-two delivery priorities and workstream ownership were established. The team agreed the initial backlog and evidence required for review.',
        highlights: ['Workstream ownership and initial priorities confirmed.', 'Source discovery and benchmark design work started.'],
        nextWeek: ['Agree assistant interaction criteria.', 'Review source fields and access needs.', 'Draft the benchmark sampling approach.'],
        attention: ['Confirm the source access route and available subject-matter reviewers.'],
        workstreams: [
          { name: 'Knowledge assistant', health: 'green', completed: ['Initial priorities agreed.'], next: ['Review interaction criteria.'], attention: [], confirmed: true },
          { name: 'Data foundation', health: 'amber', completed: ['Source inventory started.'], next: ['Confirm fields and access owners.'], attention: ['Source access route to be confirmed.'], confirmed: true },
          { name: 'Evaluation & assurance', health: 'green', completed: ['Evaluation objectives agreed.'], next: ['Draft benchmark sampling.'], attention: [], confirmed: true },
        ],
        milestones: [{ title: 'Assistant pilot accepted', forecastDate: date(4), status: 'planned' }, { title: 'Finance ingestion ready for UAT', forecastDate: date(-1), status: 'planned' }],
      },
    };
  };
  const reports = [historicalReport(1), historicalReport(2)];
  const event = (id: string, entityType: string, entityId: string, actorId: string, action: string, detail: string, hours: number, before?: unknown, after?: unknown): AuditEvent => ({ id, entityType, entityId, actorId, action, detail, createdAt: at(hours), ...(before === undefined ? {} : { before }), ...(after === undefined ? {} : { after }) });
  const events: AuditEvent[] = [
    event('event-access-raised', 'register', 'reg-finance-access', 'lead-arjun', 'created', 'Recorded finance source access dependency and named the accountable owner.', -120),
    event('event-focus-accepted', 'item', 'work-assistant-09', 'lead-leila', 'client_accepted', `Recorded client acceptance after production verification. Evidence: ${evidence('source-focus-client-acceptance')}`, -60, { stage: 'Awaiting client acceptance', cycle: 1 }, { stage: 'Closed', cycle: 1 }),
    event('event-benchmark-accepted', 'item', 'work-evaluation-01', 'lead-sara', 'closed', 'Accepted benchmark design against the documented review criteria.', -72, { stage: 'Review' }, { stage: 'Closed' }),
    event('event-feedback-verified', 'item', 'work-assistant-02', 'qa-ellie', 'transitioned', 'Production verification passed; assigned client-response recording to Leila.', -30, { stage: 'Production verification', currentOwnerId: 'qa-ellie' }, { stage: 'Awaiting client acceptance', currentOwnerId: 'lead-leila' }),
    event('event-freshness-rejected', 'item', 'work-assistant-07', 'lead-leila', 'client_rejected', `Client rejected the generic source-date wording. Reopened the same item for a full rework cycle. Evidence: ${evidence('freshness-client-response')}`, -34, { stage: 'Awaiting client acceptance', cycle: 1 }, { stage: 'Development', cycle: 2, currentOwnerId: 'dev-maya' }),
    event('event-citation-failed', 'test', 'test-citation-fail', 'qa-ellie', 'test_failed', 'UAT browser-back scenario failed; a blocking result remains open.', -28),
    event('event-data-confirmed', 'submission', 'submission-data-current', 'lead-arjun', 'confirmed', 'Confirmed the data workstream update before the revised access forecast.', -26),
    event('event-access-escalated', 'register', 'reg-finance-access', 'pmo-nadia', 'escalated', 'Escalated the overdue access dependency during the daily delivery sync.', -6, { status: 'open' }, { status: 'escalated' }),
    event('event-pilot-forecast', 'milestone', 'ms-assistant-pilot', 'lead-leila', 'forecast_changed', 'Adjusted the forecast for citation rework and final client acceptance; baseline retained.', -5, { forecastDate: date(4) }, { forecastDate: date(7) }),
    event('event-assistant-confirmed', 'submission', 'submission-assistant-current', 'lead-leila', 'confirmed', 'Confirmed current delivery facts and the revised pilot forecast.', -3),
    event('event-finance-forecast', 'milestone', 'ms-finance-ready', 'lead-arjun', 'forecast_changed', 'Revised the ingestion forecast after the access commitment was missed; existing confirmation is now stale.', -1, { forecastDate: date(-1) }, { forecastDate: date(5) }),
    ...reports.map(report => ({ id: `event-${report.id}-approved`, entityType: 'report', entityId: report.id, actorId: 'exec-omar', action: 'report_approved', detail: 'Approved the frozen client weekly snapshot after reviewing the client-safe content.', createdAt: report.approvedAt! })),
  ].sort((a, b) => b.createdAt.localeCompare(a.createdAt));

  return {
    settings: { projectName: 'Northstar · Delivery Hub', phaseName: 'Phase two', timezone: 'Asia/Dubai', submissionHour: 10, cutoffHour: 12, blockedEscalationDays: 2, workingDays: [1, 2, 3, 4, 5] },
    members, workstreams, deliverables, milestones, items, tests, registers, meetings, submissions, reports, events,
  };
}
