import { useState, useEffect, useCallback } from 'react';
import { LayoutDashboard, ListTodo, Layers3, ShieldAlert, FileText, Search, ArrowUpRight, ArrowRight, Plus, SlidersHorizontal, ChevronDown, PanelLeftClose, PanelLeftOpen, Settings2, HelpCircle, Check, X, RefreshCw, AlertTriangle, Clock3, CalendarDays, CircleCheck, Radio, MoreHorizontal, Play, Target, Users, Sparkles } from 'lucide-react';
import type { Bootstrap, PageProps, WorkItem, Milestone, Report, Settings } from '../shared/types';
import { api } from './api';
import { Avatar, Badge, Field, Modal, formatDate, healthLabel, isOverdue, canManage, canEdit, dateToday, Empty } from './ui';
import { Delivery, ItemDetail, ItemForm, MilestoneForm } from './Delivery';
import { Reports, ReportPresentation } from './Reports';
import { Registers } from './Registers';
import { MeetingWorkspace } from './Meetings';
import { WorkstreamEditor, AuditHistory } from './OverviewExtras';
import { reportingPeriod, confirmationState, recordAttention, submissionTiming } from '../shared/reporting';
const navigation = [{ id:'overview', label:'Overview', icon:LayoutDashboard },{id:'my-actions',label:'My Actions',icon:ListTodo},{id:'delivery',label:'Delivery',icon:Layers3},{id:'registers',label:'Registers',icon:ShieldAlert},{id:'reports',label:'Reports',icon:FileText}];

export default function App() { return location.pathname.startsWith('/brief/') ? <BriefRoute/> : <Workspace/>; }
function BriefRoute() {
  const [report,setReport]=useState<Report>(); const [error,setError]=useState('');
  useEffect(()=>{ api(`/api/reports/${encodeURIComponent(location.pathname.split('/')[2])}/presentation`).then(r=>setReport(r.report || r)).catch(e=>setError(e.message)); },[]);
  return <div className="presentation-shell"><div className="presentation-toolbar"><a className="button secondary" href="/#reports">← Back to workspace</a><button className="button primary" onClick={()=>window.print()}>Print / save PDF</button></div>{error?<div className="notice notice-warning">{error}</div>:report?<ReportPresentation report={report}/>:<div className="loading-screen">Opening approved brief…</div>}</div>;
}
function Workspace() {
  const [boot,setBoot]=useState<Bootstrap>(); const [error,setError]=useState(''); const [page,setPage]=useState(location.hash.slice(1)||'overview');
  const [toast,setToast]=useState<{text:string;error:boolean}>(); const [selected,setSelected]=useState<string>(); const [create,setCreate]=useState(false);
  const [settings,setSettings]=useState(false); const [meeting,setMeeting]=useState(false); const [help,setHelp]=useState(false); const [mobileNav,setMobileNav]=useState(false);
  const [search,setSearch]=useState(''); const [workstream,setWorkstream]=useState('all'); const [deliveryFilter,setDeliveryFilter]=useState('all');
  const load=useCallback(async()=>{const b=await api<Bootstrap>('/api/bootstrap');setBoot(b);setError('');return b;},[]);
  useEffect(()=>{load().catch(e=>setError(e.message)); const fn=()=>setPage(location.hash.slice(1)||'overview');window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn);},[load]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(undefined),5500);return()=>clearTimeout(timer);},[toast]);
  const notify=useCallback((text:string,error=false)=>setToast({text,error}),[]);
  const mutate=useCallback(async(path:string,body?:unknown,method?:string)=>{const result=await api(path,body,method);await load();return result;},[load]);
  function navigate(id:string,filter='all'){location.hash=id;setPage(id);setDeliveryFilter(filter);setSearch('');setMobileNav(false);}
  if(!boot)return <div className="loading-screen"><div className="brand-mark">Ⅱ</div><h1>Phase Two</h1>{error?<><p>{error}</p><button className="button primary" onClick={()=>load().catch(e=>setError(e.message))}><RefreshCw size={16}/>Try again</button></>:<><span className="loading-bar"/><p>Opening your delivery workspace…</p></>}</div>;
  const {state}=boot;const user=state.members.find(m=>m.id===boot.currentUserId)||state.members[0];
  const assigned=state.items.filter(i=>i.currentOwnerId===user.id&&i.stage!=='Closed').length;
  const props:PageProps={state,user,mutate,notify,openItem:setSelected,aiAvailable:boot.aiAvailable};
  const item=state.items.find(i=>i.id===selected);
  return <div className={`app-shell ${mobileNav?'nav-open':''}`}>
    <aside className="sidebar"><a className="brand" href="#overview"><span className="brand-mark">Ⅱ</span><span>phase two<span className="brand-sub">DELIVERY HUB</span></span></a>
      <div className="workspace-label"><span className="workspace-symbol">D</span><div><strong>{state.settings.projectName}</strong><span>{state.settings.phaseName} · Internal workspace</span></div></div>
      <div className="nav-caption">WORKSPACE</div><nav aria-label="Main navigation">{navigation.map(n=><a key={n.id} href={`#${n.id}`} onClick={()=>navigate(n.id)} className={`nav-item ${page===n.id?'active':''}`}><n.icon size={19}/><span>{n.label}</span>{n.id==='my-actions'&&assigned>0&&<span className="nav-count">{assigned}</span>}{page===n.id&&<span className="nav-current"/>}</a>)}</nav>
      <div className="sidebar-workstreams"><div className="nav-caption">WORKSTREAMS</div>{state.workstreams.map(w=><button key={w.id} className={`workstream-nav ${workstream===w.id?'selected':''}`} onClick={()=>{setWorkstream(w.id);navigate('delivery');}}><span className="stream-dot" style={{background:w.color}}/>{w.shortName}<span className="tiny-count">{state.items.filter(i=>i.workstreamId===w.id&&i.stage!=='Closed').length}</span></button>)}</div>
      <div className="sidebar-bottom"><div className="demo-card"><span className="demo-dot"/><strong>Demo workspace</strong><p>Fictional data. Real workflows.</p></div><button className="nav-item" onClick={()=>setHelp(true)}><HelpCircle size={18}/>Workspace guide<ArrowUpRight size={15}/></button><button className="nav-item" onClick={()=>setSettings(true)}><Settings2 size={18}/>Project settings</button><div className="profile"><Avatar member={user} size={36}/><div><strong>{user.name}</strong><span>{user.title}</span></div></div></div>
    </aside>
    {mobileNav&&<button className="nav-backdrop" aria-label="Close navigation" onClick={()=>setMobileNav(false)}/>}
    <main className="main-shell"><header className="topbar"><div className="breadcrumbs"><button className="icon-button mobile-toggle" onClick={()=>setMobileNav(!mobileNav)} aria-label="Toggle navigation"><PanelLeftOpen size={20}/></button><span>Workspace</span><span className="breadcrumb-slash">/</span><strong>{navigation.find(n=>n.id===page)?.label||'Overview'}</strong></div><div className="topbar-actions"><span className="private-label"><Radio size={13}/>Internal only</span><div className="persona-switch"><Avatar member={user} size={26}/><select aria-label="Demo persona" value={user.id} onChange={e=>mutate('/api/demo/persona',{userId:e.target.value}).then(()=>notify('Demo persona changed')).catch(e=>notify(e.message,true))}>{state.members.map(m=><option key={m.id} value={m.id}>{m.name} · {m.role}</option>)}</select><ChevronDown size={13}/></div><button className="icon-button" title="Refresh project data" aria-label="Refresh project data" onClick={()=>load().then(()=>notify('Project data refreshed')).catch(e=>notify(e.message,true))}><RefreshCw size={17}/></button></div></header>
    <div className="workspace-content">
      {page==='overview'&&<Overview {...props} navigate={navigate} startMeeting={()=>setMeeting(true)}/>}
      {page==='my-actions'&&<MyActions {...props} navigate={navigate}/>}
      {page==='delivery'&&<Delivery {...props} initialFilter={deliveryFilter} search={search} setSearch={setSearch} workstream={workstream} setWorkstream={setWorkstream} createItem={()=>setCreate(true)}/>}
      {page==='registers'&&<Registers {...props}/>}
      {page==='reports'&&<Reports {...props}/>}
    </div><footer className="workspace-footer"><span><span className="live-dot"/>Changes saved to this workspace</span><span>Phase Two · Fictional demonstration</span></footer></main>
    {item&&<ItemDetail {...props} item={item} onClose={()=>setSelected(undefined)}/>}
    {create&&<ItemForm {...props} onClose={()=>setCreate(false)} defaultWorkstream={workstream!=='all'?workstream:undefined}/>}
    {settings&&<ProjectSettings {...props} onClose={()=>setSettings(false)}/>}
    {meeting&&<MeetingWorkspace {...props} onClose={()=>setMeeting(false)}/>}
    {help&&<Modal title="A quieter way to run delivery" description="Your daily and weekly operating rhythm." onClose={()=>setHelp(false)}><div className="guide-steps">{[['01','Start with exceptions','Run the daily Teams meeting from Overview. Discuss blocked work, approaching dates, and decisions that need help.'],['02','Keep one working record','Use Delivery for the agreed backlog. Assignments take effect immediately. Add testing evidence to the same item through each stage.'],['03','Confirm the week','Workstream leads review their prefilled update under Reports. PMO assembles the brief and a designated manager approves the client version.'],['04','Present with confidence','Open an approved brief in presentation mode. Its saved contents stay unchanged as delivery continues.']].map(([n,t,d])=><div className="guide-step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div><div className="notice">Switch the demo persona in the top-right corner to try each role. All people and project data in this workspace are fictional.</div></Modal>}
    {toast&&<div className={`toast ${toast.error?'toast-error':''}`} role={toast.error?'alert':'status'}>{toast.error?<AlertTriangle size={18}/>:<CircleCheck size={18}/>}<span>{toast.text}</span><button onClick={()=>setToast(undefined)} aria-label="Dismiss notification"><X size={16}/></button></div>}
  </div>;
}
function Overview(props:PageProps&{navigate:(page:string,filter?:string)=>void;startMeeting:()=>void}) {
  const {state,user,openItem,navigate,startMeeting}=props; const active=state.items.filter(i=>i.stage!=='Closed');const blocked=active.filter(i=>i.blocked); const waiting=active.filter(i=>i.stage==='Awaiting client acceptance');
  const [milestone,setMilestone]=useState<Milestone>();const [createMilestone,setCreateMilestone]=useState(false);const [editStream,setEditStream]=useState<string>();const [auditOpen,setAuditOpen]=useState(false);
  const exceptions=[...active].filter(i=>i.blocked||recordAttention(i,state.settings).overdue||i.stage==='Awaiting client acceptance').sort((a,b)=>Number(b.blocked)-Number(a.blocked)||a.dueDate.localeCompare(b.dueDate)).slice(0,5);
  const currentPeriod=reportingPeriod(new Date(),state.settings.timezone,state.settings.cutoffHour);const confirmed=state.workstreams.filter(w=>confirmationState(state,w.id,currentPeriod.end).confirmed).length;const escalationCount=active.filter(i=>recordAttention(i,state.settings).escalationDue).length;
  return <><div className="page-header"><div><div className="eyebrow">{new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',timeZone:state.settings.timezone})}</div><h1 className="page-title">Delivery, in focus<span className="title-dot">.</span></h1><p className="page-subtitle">The progress, decisions, and next steps that matter today.</p></div><button className="button primary" onClick={startMeeting}><Play size={15} fill="currentColor"/>Run daily review</button></div>
    <div className="metric-grid"><button className="metric-card" onClick={()=>navigate('delivery','active')}><span className="metric-label">Active commitments<Layers3 size={17}/></span><div className="metric-value">{active.length}<span className="metric-unit">across {state.workstreams.length} workstreams</span></div><span className="metric-foot"><span className="mini-dot violet"/>{state.items.filter(i=>i.stage==='Closed'&&!!i.closedAt).length} accepted & complete<ArrowUpRight size={15}/></span></button><button className="metric-card" onClick={()=>navigate('delivery','blocked')}><span className="metric-label">Blocked work<ShieldAlert size={17}/></span><div className="metric-value">{blocked.length}<span className="metric-unit">need a next move</span></div><span className="metric-foot warn"><span className="mini-dot amber"/>{escalationCount} need escalation review<ArrowUpRight size={15}/></span></button><button className="metric-card" onClick={()=>navigate('delivery','client')}><span className="metric-label">Client acceptance<CircleCheck size={17}/></span><div className="metric-value">{waiting.length}<span className="metric-unit">awaiting confirmation</span></div><span className="metric-foot">Production verified, ready for review<ArrowUpRight size={15}/></span></button><button className="metric-card" onClick={()=>navigate('reports')}><span className="metric-label">Weekly readiness<FileText size={17}/></span><div className="metric-value">{confirmed}<span className="metric-denominator">/ {state.workstreams.length}</span><span className="metric-unit">current confirmations</span></div><span className="metric-foot">Thursday client brief<ArrowUpRight size={15}/></span></button></div>
    <div className="overview-main"><section className="panel workstreams-panel"><div className="panel-header"><div><span className="section-kicker">THE BIG PICTURE</span><h2>Workstreams</h2></div><div className="heading-inline">{['pmo','admin'].includes(user.role)&&<button className="icon-button" onClick={()=>setEditStream('new')} aria-label="Add workstream"><Plus size={17}/></button>}<button className="button ghost small" onClick={()=>navigate('delivery')}>View delivery<ArrowUpRight size={15}/></button></div></div><div className="workstreams-head"><span>Workstream</span><span>Delivery health</span><span>Accepted / total</span><span>Lead</span></div>{state.workstreams.map(w=>{const items=state.items.filter(i=>i.workstreamId===w.id),done=items.filter(i=>i.stage==='Closed'&&!!i.closedAt).length;const lead=state.members.find(m=>m.id===w.leadId);const age=(Date.now()-new Date(w.updatedAt).getTime())/86400000;return <div className="workstream-row" key={w.id}><button className="stream-title" onClick={()=>setEditStream(w.id)}><span className="stream-icon" style={{background:w.color+'18',color:w.color}}><Layers3 size={19}/></span><span><strong>{w.name}</strong><small>{w.description}</small></span></button><div><Badge tone={w.health}>{healthLabel[w.health]}</Badge>{age>7&&<small className="stale-label">Confirmation is stale</small>}</div><div className="progress-cell"><span><strong>{done}</strong> / {items.length}</span><div className="segmented-progress">{items.map(i=><i key={i.id} className={i.stage==='Closed'?'done':i.blocked?'blocked':''}/>)}</div></div><Avatar member={lead} size={32}/></div>})}<div className="panel-footnote"><span className="mini-dot green"/>Health reflects the lead’s assessment. Freshness and exceptions are tracked separately.</div></section>
    <section className="weekly-card"><div className="weekly-card-top"><span className="weekly-icon"><FileText size={22}/></span><span className="tag">THURSDAY RITUAL</span></div><h2>One update.<br/>A clearer week.</h2><p>Review what changed, confirm what comes next, and prepare your client brief.</p><div className="weekly-readiness">{state.workstreams.map(w=>{const readiness=confirmationState(state,w.id,currentPeriod.end);const sub=readiness.confirmed;return <div key={w.id}><span className="stream-dot" style={{background:w.color}}/>{w.shortName}<span className={sub?'confirmed-indicator':'pending-indicator'}>{sub?<><Check size={13}/>Confirmed</>:<><Clock3 size={13}/>To confirm</>}</span></div>})}</div><button className="button light" onClick={()=>navigate('reports')}>Open weekly brief<ArrowRight size={17}/></button></section></div>
    <div className="overview-bottom"><section className="panel"><div className="panel-header"><div className="heading-inline"><span className="attention-icon"><Target size={19}/></span><h2>Needs attention</h2><span className="count-pill">{exceptions.length}</span></div><button className="button ghost small" onClick={()=>navigate('delivery','attention')}>View all<ArrowUpRight size={15}/></button></div>{exceptions.length===0?<Empty title="Nothing needs intervention">Your active commitments are moving without flagged exceptions.</Empty>:<div className="attention-list">{exceptions.map(i=><button className="attention-row" key={i.id} onClick={()=>openItem(i.id)}><span className={`attention-marker ${i.blocked?'amber':'violet'}`}/><div><strong>{i.title}</strong><span><b>{i.id}</b><i>·</i>{i.blocked?i.blockReason:i.stage==='Awaiting client acceptance'?'Waiting for client confirmation':i.nextAction}</span></div><div className="attention-owner"><Avatar member={state.members.find(m=>m.id===i.currentOwnerId)} size={27}/><span className={recordAttention(i,state.settings).overdue?'date-overdue':''}>{formatDate(i.dueDate)}</span></div><ArrowUpRight size={15}/></button>)}</div>}</section>
    <section className="panel milestones-panel"><div className="panel-header"><h2>On the horizon</h2>{['pmo','admin'].includes(user.role)&&<button className="icon-button" title="Add milestone" aria-label="Add milestone" onClick={()=>setCreateMilestone(true)}><Plus size={18}/></button>}</div><div className="milestone-list">{[...state.milestones].sort((a,b)=>a.forecastDate.localeCompare(b.forecastDate)).slice(0,4).map(m=><button className="milestone-row" key={m.id} onClick={()=>setMilestone(m)}><div className="milestone-date"><span>{formatDate(m.forecastDate,{month:'short'})}</span><strong>{formatDate(m.forecastDate,{day:'numeric'})}</strong></div><div><strong>{m.title}</strong><span>{m.status==='complete'?'Accepted & complete':m.status==='at_risk'?'Forecast at risk':'Upcoming milestone'}</span></div><span className={`health-pin ${m.status==='at_risk'?'amber':m.status==='complete'?'green':'violet'}`}/></button>)}</div></section></div>
    <section className="recent-activity"><div className="heading-inline" style={{justifyContent:'space-between',marginBottom:12}}><span className="section-kicker">LATEST MOVEMENT</span><button className="button ghost small" onClick={()=>setAuditOpen(true)}>View history<ArrowUpRight size={14}/></button></div><div className="activity-strip">{[...state.events].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,3).map(e=><div className="activity-item" key={e.id}><Avatar member={state.members.find(m=>m.id===e.actorId)} size={27}/><div><span>{e.detail}</span><small>{formatDate(e.createdAt)} · {state.members.find(m=>m.id===e.actorId)?.name.split(' ')[0]||'Team'}</small></div></div>)}</div></section>
    {(milestone||createMilestone)&&<MilestoneForm {...props} milestone={milestone} onClose={()=>{setMilestone(undefined);setCreateMilestone(false);}}/>}
    {auditOpen&&<AuditHistory {...props} onClose={()=>setAuditOpen(false)}/>}
    {editStream&&<WorkstreamEditor {...props} id={editStream} onClose={()=>setEditStream(undefined)}/>}
  </>;
}
function MyActions(props:PageProps&{navigate:(page:string,filter?:string)=>void}) {
  const {state,user,openItem,navigate}=props;
  const now=new Date();
  const urgency=(flags:ReturnType<typeof recordAttention>)=>Number(flags.escalationDue)*8+Number(flags.overdue)*4+Number(flags.dueToday)*2+Number(flags.dueReminder);
  const items=state.items.filter(i=>i.currentOwnerId===user.id&&i.stage!=='Closed').map(item=>({item,flags:recordAttention(item,state.settings,now)})).sort((a,b)=>urgency(b.flags)-urgency(a.flags)||a.item.dueDate.localeCompare(b.item.dueDate));
  const regs=state.registers.filter(r=>r.ownerId===user.id&&r.status!=='resolved').map(record=>({record,flags:recordAttention(record,state.settings,now)})).sort((a,b)=>urgency(b.flags)-urgency(a.flags)||a.record.dueDate.localeCompare(b.record.dueDate));
  const reminder=(flags:ReturnType<typeof recordAttention>,dueDate:string)=>[
    flags.escalationDue?'Escalation review':'',
    flags.overdue?'Overdue':flags.dueToday?'Due today':flags.dueReminder?(state.settings.workingDays.includes(new Date(`${dueDate}T12:00:00Z`).getUTCDay())?'Due next working day':'Due before next working day'):'',
  ].filter(Boolean).join(' · ');
  const periodEnd=reportingPeriod(now,state.settings.timezone,state.settings.cutoffHour).end;
  const managedStreams=state.workstreams.filter(w=>['pmo','admin'].includes(user.role)||(user.role==='lead'&&w.leadId===user.id));
  const dueSoon=items.filter(({flags})=>flags.dueToday||flags.dueReminder).length;
  return <>
    <div className="page-header"><div><div className="eyebrow">YOUR NEXT MOVES</div><h1 className="page-title">My Actions<span className="title-dot">.</span></h1><p className="page-subtitle">What needs your attention, {user.name.split(' ')[0]}.</p></div><Avatar member={user} size={48}/></div>
    <div className="actions-summary"><span><strong>{items.length}</strong> active commitments</span><span><strong>{items.filter(({flags})=>flags.overdue).length}</strong> overdue</span><span><strong>{dueSoon}</strong> due soon</span><span><strong>{regs.length}</strong> open follow-ups</span></div>
    <section className="panel"><div className="panel-header"><h2>Assigned to you</h2><Badge>{user.title}</Badge></div>{items.length?<div className="attention-list">{items.map(({item:i,flags})=><button className="attention-row" key={i.id} onClick={()=>openItem(i.id)}><div className="item-stage-icon"><ListTodo size={19}/></div><div><strong>{i.title}</strong><span>{i.id} · {i.nextAction}</span>{reminder(flags,i.dueDate)&&<span style={{color:flags.escalationDue||flags.overdue?'#a3374b':'#8c5a19',fontWeight:600}}>{reminder(flags,i.dueDate)}</span>}</div><Badge tone={flags.escalationDue?'red':i.blocked?'amber':'neutral'}>{i.blocked?'Blocked':i.stage}</Badge><span className={flags.overdue?'date-overdue':'muted'}>{formatDate(i.dueDate)}</span><ArrowUpRight size={16}/></button>)}</div>:<Empty title="Your queue is clear">Items assigned to you will appear here immediately.</Empty>}</section>
    <div className="overview-bottom">
      <section className="panel"><div className="panel-header"><h2>Your follow-ups</h2></div>{regs.length?regs.map(({record:r,flags})=><button className="attention-row" key={r.id} onClick={()=>navigate('registers')}><div><strong>{r.title}</strong><span>{r.type} · {r.nextAction}</span><span style={reminder(flags,r.dueDate)?{color:flags.escalationDue||flags.overdue?'#a3374b':'#8c5a19',fontWeight:600}:undefined}>{reminder(flags,r.dueDate)||'Upcoming follow-up'} · {formatDate(r.dueDate)}</span></div><Badge tone={flags.escalationDue?'red':'amber'}>{r.status}</Badge><ArrowUpRight size={16}/></button>):<Empty title="No open register items"/>}</section>
      <section className="panel"><div className="panel-header"><h2>Weekly responsibilities</h2></div><div className="panel-body"><p className="muted">{managedStreams.length?'Review the workstream summaries and confirm the week’s progress.':'Keep your commitments current so your workstream lead can confirm the weekly update.'}</p>
        {managedStreams.map(stream=>{
          const ready=confirmationState(state,stream.id,periodEnd);
          const timing=submissionTiming(periodEnd,state.settings,ready.confirmed?ready.submission?.confirmedAt:undefined,now);
          const status=ready.confirmed?(timing.late?'Confirmed late':'Confirmed'):ready.stale?(timing.overdue?'Reconfirmation overdue':'Needs reconfirmation'):timing.overdue?'Confirmation overdue':'Confirmation due';
          return <button className="attention-row" key={stream.id} onClick={()=>navigate('reports')}><div><strong>{stream.shortName}</strong><span>Confirm by {formatDate(timing.deadlineAt,{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:state.settings.timezone})} · {state.settings.timezone}</span></div><Badge tone={timing.overdue?'red':ready.confirmed&&!timing.late?'green':'amber'}>{status}</Badge></button>;
        })}
        {user.canApproveReports&&<div className="notice">You can approve client briefs for publication.</div>}<button className="button secondary" onClick={()=>navigate('reports')}>Open reporting<ArrowRight size={16}/></button></div></section>
    </div>
  </>;
}
function ProjectSettings({onClose,...props}:PageProps&{onClose:()=>void}) {const [form,setForm]=useState<Settings>(props.state.settings);const [busy,setBusy]=useState(false);return <Modal title="Project settings" description="A few shared rules for the whole team." onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await props.mutate('/api/settings',form,'PATCH');props.notify('Project settings saved');onClose();}catch(e){props.notify((e as Error).message,true);}finally{setBusy(false);}}}><div className="form-grid"><Field label="Project name"><input value={form.projectName} required onChange={e=>setForm({...form,projectName:e.target.value})}/></Field><Field label="Phase"><input value={form.phaseName} required onChange={e=>setForm({...form,phaseName:e.target.value})}/></Field><Field label="Project timezone"><select value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}><option>Asia/Dubai</option><option>Europe/London</option><option>UTC</option><option>Asia/Riyadh</option></select></Field><Field label="Escalate blocked work after (working days)"><input type="number" min={1} max={30} value={form.blockedEscalationDays} onChange={e=>setForm({...form,blockedEscalationDays:Number(e.target.value)})}/></Field><Field label="Thursday submission hour (0–23)"><input type="number" min={0} max={23} value={form.submissionHour} onChange={e=>setForm({...form,submissionHour:Number(e.target.value)})}/></Field><Field label="Thursday reporting cutoff (0–23)"><input type="number" min={0} max={23} value={form.cutoffHour} onChange={e=>setForm({...form,cutoffHour:Number(e.target.value)})}/></Field></div><Field label="Working days"><div className="weekday-picker">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,i)=><label key={day}><input type="checkbox" checked={form.workingDays.includes(i)} onChange={e=>setForm({...form,workingDays:e.target.checked?[...form.workingDays,i]:form.workingDays.filter(d=>d!==i)})}/>{day}</label>)}</div></Field><div className="notice">This local demonstrator uses fictional personas. Corporate sign-in and shared hosting are part of the live rollout.</div><div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Close</button>{['pmo','admin'].includes(props.user.role)&&<button disabled={busy} className="button primary">{busy?'Saving…':'Save settings'}</button>}</div></form></Modal>}
