import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, ChevronRight, Clock3, Plus, Play, Flag, AlertTriangle, FileCheck2, Activity, CalendarDays } from 'lucide-react';
import { SOFTWARE_STAGES, GENERAL_STAGES, type PageProps, type Stage, type WorkflowKind, type Milestone, type WorkItem } from '../shared/types';
import { confirmationState, reportingPeriod, recordAttention, dateInTimezone, shiftDate } from '../shared/reporting';
import { Avatar, Badge, Empty, formatDate, healthLabel, memberName } from './ui';
import { MilestoneForm } from './Delivery';
import { WorkstreamEditor, AuditHistory } from './OverviewExtras';

type DashboardProps = PageProps & {navigate:(page:string,filter?:string)=>void;startMeeting:()=>void;onStage:(kind:WorkflowKind,stage:Stage)=>void;onWorkstream:(id:string)=>void};
const stageLabel:Partial<Record<Stage,string>>={'Ready for production':'Release ready','Production verification':'Verification','Awaiting client acceptance':'Client review','In progress':'In progress'};

export default function Dashboard(props:DashboardProps) {
  const {state,user,navigate,startMeeting,onStage,onWorkstream,openItem}=props;
  const [kind,setKind]=useState<WorkflowKind>('software');const [queue,setQueue]=useState<'attention'|'blocked'|'client'>('attention');
  const [milestone,setMilestone]=useState<Milestone>();const [newMilestone,setNewMilestone]=useState(false);const [stream,setStream]=useState<string>();const [history,setHistory]=useState(false);
  const stages=kind==='software'?SOFTWARE_STAGES:GENERAL_STAGES;const group=state.items.filter(i=>i.kind===kind);
  const period=reportingPeriod(new Date(),state.settings.timezone,state.settings.cutoffHour);const ready=state.workstreams.filter(w=>confirmationState(state,w.id,period.end).confirmed).length;
  const active=state.items.filter(i=>i.stage!=='Closed');const blocked=active.filter(i=>i.blocked);const awaiting=active.filter(i=>i.stage==='Awaiting client acceptance');
  const attention=active.filter(i=>{const flags=recordAttention(i,state.settings);return i.blocked||flags.overdue||flags.dueToday||flags.dueReminder||i.stage==='Awaiting client acceptance';});
  const rank=(i:WorkItem)=>{const f=recordAttention(i,state.settings);return f.escalationDue?0:i.blocked?1:f.overdue?2:i.stage==='Awaiting client acceptance'?3:f.dueToday?4:5;};
  const queueItems=[...(queue==='blocked'?blocked:queue==='client'?awaiting:attention)].sort((a,b)=>rank(a)-rank(b)||a.dueDate.localeCompare(b.dueDate));
  const accepted=state.items.filter(i=>i.stage==='Closed'&&i.closedAt).length;const isPMO=['pmo','admin'].includes(user.role);
  const reason=(i:WorkItem)=>{const f=recordAttention(i,state.settings);return f.escalationDue?'Escalation needed':i.blocked?'Blocked':f.overdue?'Target date missed':i.stage==='Awaiting client acceptance'?'Client response needed':f.dueToday?'Due today':'Due next working day';};
  const queueCount=queue==='blocked'?blocked.length:queue==='client'?awaiting.length:attention.length;
  const registerExceptions=state.registers.map(record=>({record,flags:recordAttention(record,state.settings)}))
    .filter(({record,flags})=>record.status!=='resolved'&&(record.status==='escalated'||flags.overdue||flags.dueToday))
    .sort((a,b)=>Number(b.flags.alreadyEscalated)-Number(a.flags.alreadyEscalated)||Number(b.flags.escalationDue)-Number(a.flags.escalationDue)||Number(b.flags.overdue)-Number(a.flags.overdue)||a.record.dueDate.localeCompare(b.record.dueDate));

  return <div className="delivery-desk">
    <div className="page-header desk-heading"><div><div className="eyebrow">{new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',timeZone:state.settings.timezone})} <span>All workstreams</span></div><h1 className="page-title">Delivery overview</h1><p className="page-subtitle">{active.length} active commitments. {accepted} with recorded acceptance or completed review.</p></div><button className="button primary" onClick={startMeeting}><Play size={15} fill="currentColor"/>Run daily review</button></div>

    <section className="pipeline-panel" aria-label="Current delivery pipeline"><div className="pipeline-heading"><div><span className="pipeline-kicker"><Activity size={16}/>Live delivery position</span><h2>Where the work stands</h2></div><div className="pipeline-switch" aria-label="Select delivery workflow"><button aria-pressed={kind==='software'} onClick={()=>setKind('software')}>Software changes <span>{state.items.filter(i=>i.kind==='software').length}</span></button><button aria-pressed={kind==='general'} onClick={()=>setKind('general')}>General work <span>{state.items.filter(i=>i.kind==='general').length}</span></button></div></div>
      <div className={`delivery-pipeline ${kind==='general'?'pipeline-general':''}`}>{stages.map((stage,index)=>{const items=group.filter(i=>i.stage===stage);const held=items.filter(i=>i.blocked&&i.stage!=='Closed').length;return <button key={stage} className={`pipeline-stage ${stage==='Closed'?'stage-closed':''}`} onClick={()=>onStage(kind,stage)} aria-label={`${stage}: ${items.length} ${kind==='software'?'software changes':'general work items'}${held?`, ${held} blocked`:''}`}><span className="stage-position">{String(index+1).padStart(2,'0')}<ChevronRight size={14}/></span><span className="pipeline-stage-name">{stageLabel[stage]||stage}</span><strong>{items.length}</strong><span className={`pipeline-stage-foot ${held?'stage-held':''}`}>{held?<><Flag size={11}/>{held} blocked</>:stage==='Closed'?'Closed records':'View work'}<ArrowUpRight size={13}/></span></button>;})}</div>
      <div className="pipeline-footnote"><span>Current item counts · each workflow has its own delivery stages</span><span>{group.filter(i=>i.stage!=='Closed').length} active <span className="pipeline-foot-dot">·</span> {group.filter(i=>i.stage==='Closed').length} closed</span></div>
    </section>

    <div className="desk-grid"><div className="desk-review-column"><section className="panel intervention-panel"><div className="panel-header"><div><div className="section-label">Your daily review</div><h2>Needs a next move <span className="count-pill">{queueCount}</span></h2></div><button className="text-button" onClick={()=>navigate('delivery',queue==='blocked'?'blocked':queue==='client'?'client':'attention')}>View all<ArrowUpRight size={15}/></button></div><div className="queue-tabs" aria-label="Filter action queue"><button aria-pressed={queue==='attention'} onClick={()=>setQueue('attention')}>All attention</button><button aria-pressed={queue==='blocked'} onClick={()=>setQueue('blocked')}>Blocked <span>{blocked.length}</span></button><button aria-pressed={queue==='client'} onClick={()=>setQueue('client')}>Client review <span>{awaiting.length}</span></button></div>
        <div className="intervention-list">{queueItems.slice(0,5).map((i,index)=><button className="intervention-row" key={i.id} onClick={()=>openItem(i.id)}><span className={`intervention-index ${i.blocked?'index-warning':''}`}>{i.blocked?<Flag size={15}/>:String(index+1).padStart(2,'0')}</span><div className="intervention-copy"><span className={`intervention-reason ${i.blocked?'reason-warning':''}`}>{reason(i)}<span>{state.workstreams.find(w=>w.id===i.workstreamId)?.shortName}</span></span><strong>{i.title}</strong><p>{i.nextAction||i.blockReason||'Open the item to define the next action.'}</p><div className="intervention-meta"><Avatar member={state.members.find(m=>m.id===i.currentOwnerId)} size={23}/><span>{memberName(state,i.currentOwnerId)}</span><span className="dot-separator">·</span><span>{formatDate(i.dueDate)}</span></div></div><ArrowUpRight size={18}/></button>)}{!queueItems.length&&<Empty title="This queue is clear">No work currently needs this type of intervention.</Empty>}</div>{queueItems.length>5&&<button className="queue-more" onClick={()=>navigate('delivery',queue==='blocked'?'blocked':queue==='client'?'client':'attention')}>See all {queueItems.length} items<ArrowRight size={15}/></button>}</section>

      {registerExceptions.length>0&&<section className="panel desk-register-exceptions" aria-label="Register follow-ups needing attention"><div className="panel-header"><div><span className="section-label">Overdue, escalated, or due today</span><h2>Register follow-ups <span className="count-pill">{registerExceptions.length}</span></h2></div><button className="text-button" onClick={()=>navigate('registers')}>View registers<ArrowUpRight size={15}/></button></div><div className="register-exception-list">{registerExceptions.slice(0,3).map(({record,flags})=><button className="register-exception-row" key={record.id} onClick={()=>navigate('registers')}><div className="register-exception-copy"><strong>{record.title}</strong><p>{record.nextAction||'Next action not recorded.'}</p><span className="register-exception-meta">{memberName(state,record.ownerId)} · Due {formatDate(record.dueDate)} · {record.type}</span></div><Badge tone={flags.escalationDue?'red':flags.overdue?'amber':'neutral'}>{flags.alreadyEscalated?'Escalated':flags.escalationDue?'Escalation review':flags.overdue?'Overdue':'Due today'}</Badge><ArrowUpRight size={16}/></button>)}</div>{registerExceptions.length>3&&<button className="queue-more" onClick={()=>navigate('registers')}>Review all {registerExceptions.length} register follow-ups<ArrowRight size={15}/></button>}</section>}
      </div>

      <aside className="desk-aside"><section className="panel thursday-panel"><div className="panel-header"><div><span className="section-label">Week ending {formatDate(period.end)}</span><h2>This Thursday</h2></div><FileCheck2 size={23}/></div><div className="thursday-body"><div className="readiness-heading"><strong>{ready}<span> / {state.workstreams.length}</span></strong><p>workstreams<br/>confirmed</p></div><div className="readiness-track" aria-label={`${ready} of ${state.workstreams.length} workstreams confirmed`}>{state.workstreams.map(w=><span key={w.id} className={confirmationState(state,w.id,period.end).confirmed?'ready':''}/>)}</div><div className="confirmation-rows">{state.workstreams.map(w=>{const status=confirmationState(state,w.id,period.end);return <button key={w.id} onClick={()=>navigate('reports')}><span>{w.shortName}</span><span className={status.confirmed?'text-success':'text-attention'}>{status.confirmed?<Check size={14}/>:<Clock3 size={14}/>} {status.confirmed?'Confirmed':status.stale?'Review again':'To confirm'}</span></button>;})}</div><button className="button secondary block-button" onClick={()=>navigate('reports')}>Prepare weekly report<ArrowRight size={16}/></button><p className="deadline-note">Updates by {String(state.settings.submissionHour).padStart(2,'0')}:00 · {state.settings.timezone}</p></div></section>
        <section className="panel milestone-outlook"><div className="panel-header"><div><span className="section-label">Dates that matter</span><h2>Milestone outlook</h2></div>{isPMO&&<button className="icon-button" aria-label="Add milestone" onClick={()=>setNewMilestone(true)}><Plus size={18}/></button>}</div><MilestoneOutlook milestones={state.milestones} timezone={state.settings.timezone} open={setMilestone}/></section>
      </aside>
    </div>

    <section className="panel workstream-position"><div className="panel-header"><div><span className="section-label">Delivery, in context</span><h2>Workstream position</h2></div>{isPMO&&<button className="button secondary small" onClick={()=>setStream('new')}><Plus size={15}/>Add workstream</button>}</div><div className="distribution-legend"><span><i className="dist-queued"/>Queued</span><span><i className="dist-active"/>Active work</span><span><i className="dist-client"/>Client review</span><span><i className="dist-closed"/>Closed</span><small>Item distribution, not effort complete</small></div>
      {state.workstreams.map((w,index)=>{const items=state.items.filter(i=>i.workstreamId===w.id);const parts=[items.filter(i=>i.stage==='Backlog').length,items.filter(i=>!['Backlog','Closed','Awaiting client acceptance'].includes(i.stage)).length,items.filter(i=>i.stage==='Awaiting client acceptance').length,items.filter(i=>i.stage==='Closed').length];const closed=items.filter(i=>i.stage==='Closed'&&i.closedAt).length;const imported=items.filter(i=>i.stage==='Closed'&&!i.closedAt).length;return <div className="position-row" key={w.id}><span className="workstream-number">0{index+1}</span><div className="position-title"><button className="text-button" onClick={()=>onWorkstream(w.id)}><strong>{w.name}</strong><ArrowUpRight size={14}/></button><span>{memberName(state,w.leadId)}</span></div><button className="health-review" onClick={()=>setStream(w.id)}><Badge tone={w.health}>{healthLabel[w.health]}</Badge><span>{w.statusNote||'Assessment not yet recorded.'}</span></button><button className="distribution" onClick={()=>onWorkstream(w.id)} aria-label={`${w.name}: ${parts[0]} queued, ${parts[1]} active, ${parts[2]} awaiting client, ${parts[3]} closed`}><div className="distribution-bar">{parts.map((n,i)=>n>0&&<span key={i} className={['dist-queued','dist-active','dist-client','dist-closed'][i]} style={{flex:n}}/>)}</div><div className="distribution-label"><strong>{items.length} items</strong><span>{closed} accepted / reviewed{imported?` · ${imported} imported closed`:''}</span></div></button></div>;})}
    </section>
    <div className="history-entry"><span><Activity size={16}/>Every handoff leaves a record.</span><button className="text-button" onClick={()=>setHistory(true)}>View project history<ArrowUpRight size={15}/></button></div>
    {(milestone||newMilestone)&&<MilestoneForm {...props} milestone={milestone} onClose={()=>{setMilestone(undefined);setNewMilestone(false);}}/>}{stream&&<WorkstreamEditor {...props} id={stream} onClose={()=>setStream(undefined)}/>} {history&&<AuditHistory {...props} onClose={()=>setHistory(false)}/>}
  </div>;
}

function MilestoneOutlook({milestones,timezone,open}:{milestones:Milestone[];timezone:string;open:(m:Milestone)=>void}) {
  const today=dateInTimezone(new Date(),timezone);const start=shiftDate(today,-7);const end=shiftDate(today,35);const range=42*86400000;
  const position=(date:string)=>Math.max(2,Math.min(98,(new Date(date).getTime()-new Date(start).getTime())/range*100));
  const chosen=[...milestones].sort((a,b)=>Number(a.status==='complete')-Number(b.status==='complete')||a.forecastDate.localeCompare(b.forecastDate)).slice(0,3);
  return <div className="outlook-body"><div className="outlook-range"><span>{formatDate(start)}</span><span>6-week view</span><span>{formatDate(end)}</span></div>{chosen.map(m=>{const displayedDate=m.actualDate||m.forecastDate;return <button key={m.id} className="outlook-row" onClick={()=>open(m)}><div><strong>{m.title}</strong>{m.status==='at_risk'?<AlertTriangle size={14}/>:<ChevronRight size={14}/>}</div><div className="outlook-track" aria-hidden="true"><i className="outlook-today" style={{left:`${position(today)}%`}}/><i className="outlook-shift" style={{left:`${Math.min(position(m.baselineDate),position(displayedDate))}%`,width:`${Math.abs(position(displayedDate)-position(m.baselineDate))}%`}}/><i className="outlook-baseline" style={{left:`${position(m.baselineDate)}%`}}/><i className={`outlook-forecast ${m.status==='at_risk'?'at-risk':''}`} style={{left:`${position(displayedDate)}%`}}/></div><div className="outlook-dates"><span>Baseline {formatDate(m.baselineDate)}</span><strong>{m.actualDate?'Actual':'Forecast'} {formatDate(displayedDate)}</strong></div>{(displayedDate<start||displayedDate>end)&&<small className="muted">Date falls outside the displayed range</small>}</button>;})}{!chosen.length&&<Empty title="No milestones yet"/>}<div className="outlook-key"><span><i/>Baseline</span><span><i/>Forecast / actual</span><span>│ Today</span></div></div>;
}
