import { useState, useEffect, useMemo, useRef, type FormEvent } from 'react';
import { Search, Plus, Upload, Download, LayoutList, Columns3, ArrowUpRight, ArrowRight, ArrowLeft, CheckCircle2, Circle, AlertTriangle, Link2, Pencil, RotateCcw, ShieldCheck, X, ChevronDown, SlidersHorizontal } from 'lucide-react';
import { type PageProps, type WorkItem, type Stage, type WorkflowKind, type TestResult, type ImportPreview, type Milestone, type Deliverable, type HubState, type Member } from '../shared/types';
import { Avatar, Badge, Empty, Field, Modal, SafeLink, canEdit, formatDate, memberName } from './ui';
import { recordAttention } from '../shared/reporting';
import { workflowStages, selectDeliveryItems, deliveryPrerequisites, handoffLabel, itemStageLabel, type DeliverySort } from './delivery-model';
import './delivery.css';

function isPMO(user:Member){return user.role==='pmo'||user.role==='admin';}
function canEditOwnedRecord(state:HubState,user:Member,record:{ownerId:string;workstreamId?:string;workstreamIds?:string[]}){
  const streams=record.workstreamIds||(record.workstreamId?[record.workstreamId]:[]);
  return canEdit(user)&&(isPMO(user)||record.ownerId===user.id||(user.role==='lead'&&state.workstreams.some(stream=>streams.includes(stream.id)&&stream.leadId===user.id)));
}
function canEditItem(state:HubState,user:Member,item:WorkItem){
  const creator=item.stage==='Backlog'&&state.events.some(event=>event.entityId===item.id&&event.action==='created'&&event.actorId===user.id);
  return canEdit(user)&&item.stage!=='Closed'&&(canEditOwnedRecord(state,user,item)||item.currentOwnerId===user.id||creator);
}
type DeliveryProps=PageProps&{initialFilter:string;initialTab?:'work'|'milestones';initialStage?:Stage;initialKind?:WorkflowKind;search:string;setSearch:(s:string)=>void;workstream:string;setWorkstream:(s:string)=>void;createItem:()=>void};
const stateLabels:Record<string,string>={all:'All work',active:'Active work',intervention:'Needs intervention',escalation:'Escalation due','due-soon':'Additional due soon',overdue:'Past target',blocked:'Blocked work',attention:'All attention items',client:'Awaiting client acceptance',closed:'Closed work'};

export function Delivery(props:DeliveryProps){
  const {state,user,openItem,search,setSearch,workstream,setWorkstream,createItem}=props;
  const [status,setStatus]=useState(props.initialFilter);
  const [kind,setKind]=useState<WorkflowKind|'all'>(props.initialKind||'all');
  const [stage,setStage]=useState<Stage|'all'>(props.initialStage||'all');
  const [owner,setOwner]=useState('all');const [sort,setSort]=useState<DeliverySort>('attention');
  const [view,setView]=useState<'list'|'board'>('list');const [tab,setTab]=useState<string>(props.initialTab||'work');
  const [filtersOpen,setFiltersOpen]=useState(false);const [mobileStage,setMobileStage]=useState<Stage>(props.initialStage||'Backlog');
  const [importOpen,setImportOpen]=useState(false);const [milestone,setMilestone]=useState<Milestone>();const [newMilestone,setNewMilestone]=useState(false);const [deliverable,setDeliverable]=useState<Deliverable|'new'>();
  useEffect(()=>{setStatus(props.initialFilter);setStage(props.initialStage||'all');setKind(props.initialKind||'all');setMobileStage(props.initialStage||'Backlog');setView('list');setTab(props.initialTab||'work');},[props.initialFilter,props.initialStage,props.initialKind,props.initialTab]);
  const filtered=useMemo(()=>selectDeliveryItems(state,{query:search,workstream,owner,status,kind,stage,sort}),[state,search,workstream,owner,status,kind,stage,sort]);
  useEffect(()=>{if(filtered.length&&!filtered.some(item=>item.stage===mobileStage))setMobileStage(filtered[0].stage);},[filtered]);
  const boardKind:WorkflowKind=kind==='general'?'general':'software';const boardStages=workflowStages(boardKind);
  const filteredContext=[kind!=='all'?(kind==='software'?'Software changes':'General work'):'',workstream!=='all'?state.workstreams.find(w=>w.id===workstream)?.shortName:'',owner!=='all'?(owner==='unassigned'?'Unassigned':memberName(state,owner)):'',status!=='all'?stateLabels[status]:''].filter(Boolean);
  const hasFilters=!!search||workstream!=='all'||owner!=='all'||status!=='all'||kind!=='all'||stage!=='all';
  function chooseKind(value:WorkflowKind|'all'){setKind(value);setStage('all');setMobileStage('Backlog');if(value==='all')setView('list');}
  function clearFilters(){setSearch('');setWorkstream('all');setOwner('all');setStatus('all');setKind('all');setStage('all');setView('list');}
  function chooseView(value:'list'|'board'){if(value==='board'&&kind==='all'){setKind('software');setStage('all');setMobileStage('Backlog');}setView(value);}
  function itemDate(item:WorkItem){const attention=recordAttention(item,state.settings);return <span className={'desk-date '+(attention.overdue?'is-overdue':'')}><strong>{item.dueDate?formatDate(item.dueDate):'Not set'}</strong>{attention.overdue?<small>Overdue</small>:attention.dueToday&&<small>Due today</small>}</span>;}
  function ownerCell(item:WorkItem){return <span className="desk-person"><Avatar member={state.members.find(m=>m.id===item.currentOwnerId)} size={28}/><span>{item.currentOwnerId?memberName(state,item.currentOwnerId):'Unassigned'}</span></span>;}
  return <div className="delivery-desk">
    <header className="page-header"><div><h1 className="page-title">Delivery</h1><p className="page-subtitle">Clear next steps. Visible handovers. A complete delivery record.</p></div><div className="desk-header-actions">{isPMO(user)&&<details className="desk-export-menu"><summary className="button secondary"><Download size={16}/>Import / export<ChevronDown size={14}/></summary><div><button className="button ghost" onClick={()=>setImportOpen(true)}><Upload size={16}/>Import a backlog</button><a className="button ghost" href="/api/export?format=xlsx" download>Download workbook</a><a className="button ghost" href="/api/export?format=csv" download>Download work as CSV</a></div></details>}{canEdit(user)&&<button className="button primary" onClick={createItem}><Plus size={17}/>Add work</button>}</div></header>
    <nav className="desk-section-tabs" aria-label="Delivery sections">{[['work','Work items',state.items.length],['milestones','Milestones',state.milestones.length],['deliverables','Deliverables',state.deliverables.length]].map(([value,label,count])=><button key={value} className={tab===value?'active':''} aria-current={tab===value?'page':undefined} onClick={()=>setTab(String(value))}>{label}<span>{count}</span></button>)}</nav>
    {tab==='work'&&<>
      <section className="desk-controls" aria-label="Find delivery work">
        <div className="desk-search-row"><div className="search-input"><Search size={18}/><input aria-label="Search delivery work" placeholder="Find work, a next action, or an owner…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button className="icon-button" onClick={()=>setSearch('')} aria-label="Clear search"><X size={16}/></button>}</div><button className="button secondary desk-filter-toggle" aria-expanded={filtersOpen} aria-controls="delivery-filters" onClick={()=>setFiltersOpen(!filtersOpen)}><SlidersHorizontal size={16}/>Filters</button><div className="desk-view-switch" aria-label="Display work"><button aria-pressed={view==='list'} className={view==='list'?'active':''} onClick={()=>chooseView('list')}><LayoutList size={17}/>List</button><button aria-pressed={view==='board'} className={view==='board'?'active':''} onClick={()=>chooseView('board')}><Columns3 size={17}/>Board</button></div></div>
        <div id="delivery-filters" className={'desk-filter-grid '+(filtersOpen?'is-open':'')}><Field label="Workstream"><select value={workstream} onChange={e=>setWorkstream(e.target.value)}><option value="all">All workstreams</option>{state.workstreams.map(w=><option key={w.id} value={w.id}>{w.shortName}</option>)}</select></Field><Field label="Next action owner"><select value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">Everyone</option><option value="unassigned">Unassigned</option>{state.members.filter(m=>m.role!=='executive').map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="State"><select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(stateLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Sort by"><select value={sort} onChange={e=>setSort(e.target.value as DeliverySort)}><option value="attention">Attention needed</option><option value="due">Target date</option><option value="priority">Priority</option><option value="title">Work title</option></select></Field></div>
        <div className="desk-workflow-row"><div className="desk-workflow-switch" aria-label="Delivery workflow">{(['all','software','general'] as const).map(value=><button key={value} aria-pressed={kind===value} className={kind===value?'active':''} onClick={()=>chooseKind(value)}>{value==='all'?'All workflows':value==='software'?'Software changes':'General work'}</button>)}</div><span className="desk-result-count" role="status">{filtered.length} {filtered.length===1?'item':'items'}</span></div>
      </section>
      {hasFilters&&<div className="desk-filter-summary"><span>{filteredContext.join(' · ')||'Filtered work'}{search?' · “'+search+'”':''}</span>{stage!=='all'&&<button className="desk-filter-chip" onClick={()=>setStage('all')} aria-label={'Remove stage filter '+stage}>{stage}<X size={13}/></button>}<button className="button ghost small" onClick={clearFilters}>Clear filters</button></div>}
      {view==='list'?<section className="panel desk-list-panel" aria-label="Delivery work list"><table className="desk-work-table"><thead><tr><th>Work / next action</th><th>Delivery stage</th><th>Next action owner</th><th>Target</th><th>Priority</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id} className={item.blocked&&item.stage!=='Closed'?'has-blocker':''}><td><button className="desk-work-link" onClick={()=>openItem(item.id)}><strong>{item.title}</strong><ArrowUpRight size={16}/></button><p className={'desk-next-action '+(item.blocked&&item.stage!=='Closed'?'is-blocked':'')}>{item.blocked&&item.stage!=='Closed'&&<AlertTriangle size={14}/>}<span>{item.blocked&&item.stage!=='Closed'?'Blocked: '+item.blockReason:item.nextAction||'Define the next action before work starts.'}</span></p><span className="desk-work-reference">{state.workstreams.find(w=>w.id===item.workstreamId)?.shortName} · {item.id}</span></td><td data-label="Stage"><Badge tone={item.stage==='Closed'?'green':item.stage==='Awaiting client acceptance'?'blue':'neutral'}>{itemStageLabel(item)}</Badge></td><td data-label="Next action owner">{ownerCell(item)}</td><td data-label="Target">{itemDate(item)}</td><td data-label="Priority"><span className={'desk-priority priority-'+item.priority.toLowerCase()}>{item.priority}</span></td></tr>)}</tbody></table>{!filtered.length&&<Empty title="No work matches these filters">Broaden the filters to find the work you need. <button className="button secondary" onClick={clearFilters}>Clear filters</button></Empty>}<footer className="desk-list-footer"><span>Open a work item to update it or hand it over.</span><span>Accountable ownership stays visible in the delivery record.</span></footer></section>:<>
        <div className="desk-board-guide"><p>{boardKind==='software'?'Software changes move through testing, deployment, and client acceptance.':'General work moves from delivery into review and acceptance.'}</p><Field label="Visible stage"><select value={mobileStage} onChange={e=>setMobileStage(e.target.value as Stage)}>{boardStages.map(s=><option value={s} key={s}>{s} ({filtered.filter(i=>i.stage===s).length})</option>)}</select></Field></div>
        <div className="desk-board" aria-label={(boardKind==='software'?'Software':'General work')+' delivery board'}>{boardStages.map(s=><section key={s} className="desk-board-lane" data-mobile-active={mobileStage===s}><header><h2>{s}</h2><span>{filtered.filter(i=>i.stage===s).length}</span></header><div className="desk-board-items">{filtered.filter(i=>i.stage===s).map(item=><button className="desk-board-card" key={item.id} onClick={()=>openItem(item.id)}><span className="desk-work-reference">{state.workstreams.find(w=>w.id===item.workstreamId)?.shortName}</span><strong>{item.title}</strong>{item.blocked&&item.stage!=='Closed'&&<Badge tone="amber">Blocked</Badge>}{item.stage==='Closed'&&item.importedFrom&&!item.closedAt&&<Badge tone="neutral">Imported closed</Badge>}<p>{item.blocked&&item.stage!=='Closed'?item.blockReason:item.nextAction||'Next action not yet defined.'}</p><footer>{ownerCell(item)}{itemDate(item)}</footer></button>)}{!filtered.some(i=>i.stage===s)&&<p className="desk-empty-lane">No work at this stage</p>}</div></section>)}</div>
      </>}
    </>}
    {tab==='milestones'&&<section className="desk-outcome-section"><div className="desk-section-heading"><p className="muted">Baseline commitments alongside the current delivery forecast.</p>{isPMO(user)&&<button className="button primary" onClick={()=>setNewMilestone(true)}><Plus size={16}/>Add milestone</button>}</div><div className="panel desk-milestones">{state.milestones.map(m=><button className="desk-milestone-row" key={m.id} onClick={()=>setMilestone(m)}><div><Badge tone={m.status==='at_risk'?'amber':m.status==='complete'?'green':'neutral'}>{m.status==='at_risk'?'At risk':m.status==='complete'?'Complete':'Planned'}</Badge><h2>{m.title}</h2><p>{m.notes||'No delivery note yet.'}</p><span className="desk-work-reference">{memberName(state,m.ownerId)}</span></div><dl><div><dt>Baseline</dt><dd>{formatDate(m.baselineDate)}</dd></div><div><dt>Forecast</dt><dd>{formatDate(m.forecastDate)}</dd></div><div><dt>Actual</dt><dd>{m.actualDate?formatDate(m.actualDate):'Not recorded'}</dd></div></dl><ArrowUpRight size={19}/></button>)}{!state.milestones.length&&<Empty title="No milestones recorded">Add the next commitment the team needs to meet.</Empty>}</div></section>}
    {tab==='deliverables'&&<section className="desk-outcome-section"><div className="desk-section-heading"><p className="muted">The outcomes this work contributes to.</p>{canEdit(user)&&(isPMO(user)||state.workstreams.some(w=>user.workstreamIds.includes(w.id)))&&<button className="button primary" onClick={()=>setDeliverable('new')}><Plus size={16}/>Add deliverable</button>}</div><div className="desk-deliverables">{state.deliverables.map(d=><article className="panel desk-deliverable" key={d.id}><header><div><span className="desk-work-reference">{state.workstreams.find(w=>w.id===d.workstreamId)?.shortName} · {memberName(state,d.ownerId)}</span><h2>{d.title}</h2><p>{d.description||'No outcome description yet.'}</p></div>{canEditOwnedRecord(state,user,d)&&<button className="button secondary small" onClick={()=>setDeliverable(d)}><Pencil size={14}/>Edit</button>}</header><div className="desk-deliverable-work">{state.items.filter(i=>i.deliverableId===d.id).map(i=><button key={i.id} onClick={()=>openItem(i.id)}><span>{i.title}</span><Badge tone={i.stage==='Closed'?'green':'neutral'}>{itemStageLabel(i)}</Badge><ArrowUpRight size={15}/></button>)}{!state.items.some(i=>i.deliverableId===d.id)&&<p className="muted">No work items linked yet. Link work from its delivery record.</p>}</div></article>)}{!state.deliverables.length&&<Empty title="No deliverables recorded">Group work around a concrete project outcome.</Empty>}</div></section>}
    {importOpen&&<ImportDialog {...props} onClose={()=>setImportOpen(false)}/>}{(milestone||newMilestone)&&<MilestoneForm {...props} milestone={milestone} onClose={()=>{setMilestone(undefined);setNewMilestone(false);}}/>}{deliverable&&<DeliverableForm {...props} value={deliverable==='new'?undefined:deliverable} onClose={()=>setDeliverable(undefined)}/>}
  </div>;
}

type ItemContext='none'|'handoff'|'test'|'resolve'|'rework'|'client'|'edit';
export function ItemDetail({item,onClose,...props}:PageProps&{item:WorkItem;onClose:()=>void}){
  const {state,user,mutate,notify}=props;
  const [tab,setTab]=useState<'summary'|'checks'|'history'>('summary');const [context,setContext]=useState<ItemContext>('none');
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [showStages,setShowStages]=useState(false);
  const [operation,setOperation]=useState({version:item.version,cycle:item.cycle,stage:item.stage});
  const [nextOwner,setNextOwner]=useState(item.currentOwnerId);const [evidence,setEvidence]=useState('');const [notes,setNotes]=useState('');
  const [testResult,setTestResult]=useState<'pass'|'fail'>('pass');const [blocking,setBlocking]=useState(true);const [resolveId,setResolveId]=useState('');
  const [clientDecision,setClientDecision]=useState<'accepted'|'rejected'>('accepted');
  const contextHeading=useRef<HTMLHeadingElement>(null);const checksSection=useRef<HTMLElement>(null);
  const editable=canEdit(user);const metadataEditable=canEditItem(state,user,item);
  const tests=state.tests.filter(t=>t.itemId===item.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  const currentTests=tests.filter(t=>t.cycle===item.cycle);const previousTests=tests.filter(t=>t.cycle!==item.cycle);
  const requirements=deliveryPrerequisites(state,item,nextOwner,evidence);const missing=requirements.checks.filter(c=>!c.met);
  const sourceMissing=missing.filter(c=>c.action!=='handoff');const needsDefinition=sourceMissing.some(c=>c.action==='definition');
  const stageCheckMissing=sourceMissing.some(c=>c.action==='checks');
  const canPass=['UAT','Production verification','Review'].includes(operation.stage);
  const effectiveResult=canPass?testResult:'fail';
  const stale=operation.version!==item.version||operation.cycle!==item.cycle||operation.stage!==item.stage;
  const stages=workflowStages(item.kind);const currentIndex=stages.indexOf(item.stage);
  const priorUnresolved=previousTests.filter(t=>t.result==='fail'&&t.blocking&&!t.resolvedAt);
  const selectedFinding=tests.find(t=>t.id===resolveId);
  const attention=recordAttention(item,state.settings);
  useEffect(()=>{setContext('none');setTab('summary');setError('');setShowStages(false);},[item.id]);
  useEffect(()=>{if(context!=='none'&&context!=='edit'){contextHeading.current?.focus({preventScroll:true});contextHeading.current?.scrollIntoView({block:'nearest'});}},[context,resolveId]);
  function showChecks(){setTab('checks');requestAnimationFrame(()=>checksSection.current?.scrollIntoView({block:'nearest'}));}
  function begin(value:ItemContext,findingId=''){
    setOperation({version:item.version,cycle:item.cycle,stage:item.stage});setError('');setNotes('');setEvidence('');setResolveId(findingId);setTestResult('pass');setBlocking(true);setClientDecision('accepted');
    setNextOwner(value==='rework'||value==='client'?item.ownerId:item.currentOwnerId);setContext(value);
    if(value==='test'||value==='resolve')setTab('checks');
  }
  async function run(path:string,data:unknown,message:string){
    if(busy)return;setBusy(true);setError('');
    try{await mutate(path,data);notify(message);setContext('none');setNotes('');setEvidence('');}
    catch(e){const message=(e as Error).message;setError(message);notify(message,true);}
    finally{setBusy(false);}
  }
  function renderPrerequisites(onlyMissing=false){
    const rows=onlyMissing?missing:requirements.checks;
    return <ul className="desk-prerequisites">{rows.map(c=><li key={c.key} className={c.met?'is-met':'is-missing'}>{c.met?<CheckCircle2 size={16}/>:<Circle size={16}/>}<span>{c.label}</span></li>)}</ul>;
  }
  function renderTest(t:TestResult){
    return <article className="desk-check-record" key={t.id}><header><Badge tone={t.result==='pass'?'green':t.resolvedAt?'neutral':t.blocking?'red':'amber'}>{t.result==='pass'?'Passed':t.resolvedAt?'Resolved':t.blocking?'Blocking finding':'Finding'}</Badge><span>{t.stage} · Cycle {t.cycle}</span><time dateTime={t.createdAt}>{formatDate(t.createdAt)}</time></header><p>{t.notes}</p><div className="desk-evidence"><Link2 size={15}/><SafeLink href={t.evidence}/></div>{t.resolution&&<div className="desk-resolution"><strong>Resolution</strong><p>{t.resolution}</p><span>{memberName(state,t.resolvedBy||'')} · {formatDate(t.resolvedAt)}</span></div>}<footer><span>Recorded by {memberName(state,t.authorId)}</span>{editable&&t.result==='fail'&&!t.resolvedAt&&<button className="button secondary small" onClick={()=>begin('resolve',t.id)}>Record resolution</button>}</footer></article>;
  }
  const contextTitles:Record<ItemContext,string>={none:'',handoff:handoffLabel(item),test:canPass?'Record a stage check':'Record a finding',resolve:'Resolve a finding',rework:'Start a rework cycle',client:'Record the client response',edit:'Edit work details'};
  return <Modal variant="drawer" className="desk-item-drawer" title={item.title} description={item.id+' · Delivery cycle '+item.cycle+' · '+(state.workstreams.find(w=>w.id===item.workstreamId)?.name||'')} onClose={onClose}>
    <div className="desk-item-state"><Badge tone={item.stage==='Closed'?'green':item.stage==='Awaiting client acceptance'?'blue':'neutral'}>{itemStageLabel(item)}</Badge>{item.blocked&&item.stage!=='Closed'&&<Badge tone="amber">Blocked</Badge>}<span className={'desk-priority priority-'+item.priority.toLowerCase()}>{item.priority} priority</span><button className="button ghost small" aria-expanded={showStages} onClick={()=>setShowStages(!showStages)}>{showStages?'Hide workflow':'View workflow'}<ChevronDown size={14}/></button></div>
    {showStages&&<ol className="desk-stage-trail" aria-label="Delivery workflow">{stages.map((s,index)=><li key={s} className={index===currentIndex?'current':index<currentIndex?'previous':''} aria-current={index===currentIndex?'step':undefined}><span>{index+1}</span>{s}</li>)}</ol>}
    <dl className="desk-item-ownership"><div><dt>Accountable owner</dt><dd><Avatar member={state.members.find(m=>m.id===item.ownerId)} size={27}/>{memberName(state,item.ownerId)}</dd></div><div><dt>Next action owner</dt><dd><Avatar member={state.members.find(m=>m.id===item.currentOwnerId)} size={27}/>{memberName(state,item.currentOwnerId)}</dd></div><div><dt>Target date</dt><dd className={attention.overdue?'is-overdue':''}>{item.dueDate?formatDate(item.dueDate):'Not set'}{attention.overdue&&<small>Overdue</small>}</dd>{item.baselineDate&&item.baselineDate!==item.dueDate&&<small>Baseline {formatDate(item.baselineDate)}</small>}</div></dl>
    {context==='none'&&<section className={'desk-next-step '+(item.stage==='Closed'?'is-complete':'')}>
      {item.stage==='Closed'?<><div className="desk-next-heading"><CheckCircle2 size={23}/><div><h2>{item.importedFrom&&!item.closedAt?'Imported closed record':'Delivery accepted'}</h2><p>{item.importedFrom&&!item.closedAt?'The source backlog marked this work closed. No acceptance date or testing evidence was invented.':'Closed '+formatDate(item.closedAt)+'. The delivery history and acceptance evidence remain available.'}</p></div></div>{editable&&<button className="button secondary" onClick={()=>begin('rework')}><RotateCcw size={15}/>Reopen for rework</button>}</>:
      item.stage==='Awaiting client acceptance'?<><div className="desk-next-heading"><ShieldCheck size={23}/><div><span className="desk-small-label">Next step</span><h2>Record the client response</h2><p>Client acceptance is the final delivery step. Record the client’s actual response and evidence before closing this work.</p></div></div>{(item.blocked||requirements.unresolved.length>0)&&<div className="notice notice-warning">Acceptance is paused until the delivery blocker and all blocking findings are resolved. A rejected response can still return the work for rework.</div>}{editable&&<div className="desk-item-actions"><button className="button primary" onClick={()=>begin('client')}>Record client response<ArrowRight size={16}/></button><button className="button secondary" onClick={showChecks}>Checks & evidence</button>{metadataEditable&&<button className="button ghost" onClick={()=>begin('edit')}>Edit details</button>}</div>}</>:
      <><div className="desk-next-heading"><ArrowRight size={22}/><div><span className="desk-small-label">Next step · {requirements.nextStage}</span><h2>{handoffLabel(item)}</h2><p>{sourceMissing.length?sourceMissing.length+' delivery prerequisite'+(sourceMissing.length===1?' needs':'s need')+' attention before this handover.':'The delivery record is ready. Confirm who acts next and add the handover evidence.'}</p></div></div>{sourceMissing.length>0&&<ul className="desk-prerequisites">{sourceMissing.map(c=><li className="is-missing" key={c.key}><Circle size={16}/><span>{c.label}</span></li>)}</ul>}<details className="desk-ready-checks"><summary>{requirements.checks.filter(c=>c.met&&c.action!=='handoff').length} prerequisites met</summary><ul className="desk-prerequisites">{requirements.checks.filter(c=>c.met&&c.action!=='handoff').map(c=><li className="is-met" key={c.key}><CheckCircle2 size={15}/><span>{c.label}</span></li>)}</ul></details>{editable&&<div className="desk-item-actions">{needsDefinition?<button className="button primary" disabled={!metadataEditable} onClick={()=>begin('edit')}><Pencil size={15}/>Complete the definition</button>:stageCheckMissing?<button className="button primary" onClick={()=>requirements.unresolved.length?showChecks():begin('test')}>{requirements.unresolved.length?'Review blocking findings':'Record stage check'}<ArrowRight size={16}/></button>:<button className="button primary" onClick={()=>begin('handoff')}>{handoffLabel(item)}<ArrowRight size={16}/></button>}{metadataEditable&&!needsDefinition&&<button className="button secondary" onClick={()=>begin('edit')}><Pencil size={14}/>Edit details</button>}{item.stage!=='Backlog'&&<button className="button ghost" onClick={()=>begin('rework')}><RotateCcw size={14}/>Start rework</button>}</div>}{editable&&needsDefinition&&!metadataEditable&&<p className="desk-help">The accountable owner, current action owner, workstream lead, or PMO can update the missing definition.</p>}</>}
      {!editable&&item.stage!=='Closed'&&<p className="desk-help">A delivery team member can record the next handover.</p>}
    </section>}
    {context!=='none'&&<section className="desk-context-form" aria-label={contextTitles[context]}><div className="desk-context-heading"><button type="button" className="button ghost small" disabled={busy} onClick={()=>{setContext('none');setError('');}}><ArrowLeft size={15}/>Back to next step</button><h2 ref={contextHeading} tabIndex={-1}>{contextTitles[context]}</h2></div>
      {context==='edit'?<ItemForm {...props} item={item} embedded onClose={()=>setContext('none')}/>:<form onSubmit={event=>{
        event.preventDefault();if(busy||stale)return;
        if(context==='handoff')run('/api/items/'+item.id+'/transition',{version:operation.version,stage:requirements.nextStage,currentOwnerId:nextOwner,evidence},'Moved to '+requirements.nextStage+'. '+memberName(state,nextOwner)+' acts next.');
        if(context==='test')run('/api/items/'+item.id+'/tests',{version:operation.version,cycle:operation.cycle,stage:operation.stage,result:effectiveResult,blocking:effectiveResult==='fail'&&blocking,notes,evidence},'Check recorded against delivery cycle '+operation.cycle+'.');
        if(context==='resolve')run('/api/test-results/'+resolveId+'/resolve',{notes},'Finding resolution recorded. Stage checks remain separate.');
        if(context==='rework')run('/api/items/'+item.id+'/reopen',{version:operation.version,reason:notes,currentOwnerId:nextOwner},'Rework cycle started.');
        if(context==='client')run('/api/items/'+item.id+'/client-response',{version:operation.version,decision:clientDecision,notes,evidence,...(clientDecision==='rejected'?{currentOwnerId:nextOwner}:{})},clientDecision==='accepted'?'Client acceptance recorded. Work closed.':'Client response recorded. Work returned to development.');
      }}>
        {error&&<div className="notice notice-warning" role="alert">{error}</div>}
        {stale&&<div className="notice notice-warning" role="alert"><p>This delivery record changed while this form was open. Review the current stage, owners, and evidence before continuing.</p><button type="button" className="button secondary small" onClick={()=>setOperation({version:item.version,cycle:item.cycle,stage:item.stage})}>Use current cycle {item.cycle} · {item.stage}</button></div>}
        {context==='handoff'&&<><p className="desk-help">This moves the work from {operation.stage} to {requirements.nextStage}. The accountable owner remains {memberName(state,item.ownerId)}.</p><Field label="Who takes the next action?"><select required value={nextOwner} onChange={e=>setNextOwner(e.target.value)}><option value="">Choose a delivery teammate</option>{state.members.filter(m=>m.role!=='executive').map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label={requirements.nextStage==='Production verification'?'Deployment evidence (required)':'Handover note or evidence'}><textarea rows={3} required={requirements.nextStage==='Production verification'} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder={requirements.nextStage==='Production verification'?'Release/build reference and where the deployment was verified':'Give the next owner the context they need.'}/></Field>{missing.length>0&&renderPrerequisites(true)}<div className="form-actions"><button className="button primary" disabled={busy||stale||!requirements.ready}>{busy?'Saving…':handoffLabel(item)}<ArrowRight size={16}/></button></div></>}
        {context==='test'&&<><p className="desk-help">Recorded against <strong>{operation.stage} · cycle {operation.cycle}</strong>. Any delivery teammate can record a check.</p>{!canPass&&<div className="notice">Passing checks belong to UAT, production verification, or general review. A blocking failure found here returns the item to active work and starts a new cycle.</div>}<Field label="Check outcome"><select value={effectiveResult} onChange={e=>setTestResult(e.target.value as 'pass'|'fail')}>{canPass&&<option value="pass">Passed</option>}<option value="fail">Failed</option></select></Field><Field label="What did you check and find?"><textarea required rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Describe the check, expected result, and actual result."/></Field><Field label="Evidence or reference"><input required value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Test run, build, document, or evidence link"/></Field>{effectiveResult==='fail'&&<label className="checkbox-label"><input type="checkbox" checked={blocking} onChange={e=>setBlocking(e.target.checked)}/>This finding blocks delivery</label>}<div className="form-actions"><button className="button primary" disabled={busy||stale||!notes.trim()||!evidence.trim()}>{busy?'Saving…':'Save check'}</button></div></>}
        {context==='resolve'&&<><blockquote className="desk-finding-quote">{selectedFinding?.notes}<footer>{selectedFinding?.stage} · Cycle {selectedFinding?.cycle}</footer></blockquote><p className="desk-help">Describe the fix and how it was verified. Resolving a finding does not add a passing stage check.</p><Field label="Resolution and verification"><textarea required rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></Field><div className="form-actions"><button className="button primary" disabled={busy||stale||!notes.trim()}>{busy?'Saving…':'Record resolution'}</button></div></>}
        {context==='rework'&&<><div className="notice">The work returns to {item.kind==='software'?'Development':'In progress'} in a new delivery cycle. Existing evidence stays in the history; new stage checks will be required.</div><Field label="Reason and next action for rework"><textarea required rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></Field><Field label="Who takes the rework?"><select required value={nextOwner} onChange={e=>setNextOwner(e.target.value)}><option value="">Choose a delivery teammate</option>{state.members.filter(m=>m.role!=='executive').map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><div className="form-actions"><button className="button primary" disabled={busy||stale||!notes.trim()||!nextOwner}>{busy?'Saving…':'Start rework cycle'}<RotateCcw size={15}/></button></div></>}
        {context==='client'&&<><p className="desk-help">Record an actual client response received by the team. This action does not send a message to the client.</p><Field label="Client decision"><select value={clientDecision} onChange={e=>setClientDecision(e.target.value as 'accepted'|'rejected')}><option value="accepted">Accepted — close this work</option><option value="rejected">Rejected — return for rework</option></select></Field><Field label="Client response and context"><textarea required rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What did the client accept, or what needs to change?"/></Field><Field label="Response evidence"><input required value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Email subject, meeting reference, or evidence link"/></Field>{clientDecision==='rejected'&&<Field label="Who takes the rework?"><select required value={nextOwner} onChange={e=>setNextOwner(e.target.value)}><option value="">Choose a delivery teammate</option>{state.members.filter(m=>m.role!=='executive').map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field>}{clientDecision==='accepted'&&(item.blocked||requirements.unresolved.length>0)&&<div className="notice notice-warning">Clear the delivery blocker and resolve all blocking findings before recording acceptance.</div>}<div className="form-actions"><button className={'button '+(clientDecision==='rejected'?'danger':'primary')} disabled={busy||stale||!notes.trim()||!evidence.trim()||(clientDecision==='accepted'&&(item.blocked||requirements.unresolved.length>0))||(clientDecision==='rejected'&&!nextOwner)}>{busy?'Saving…':clientDecision==='accepted'?'Record acceptance & close':'Record rejection & start rework'}</button></div></>}
      </form>}
    </section>}
    <nav className="desk-section-tabs desk-detail-tabs" aria-label="Work record sections"><button className={tab==='summary'?'active':''} aria-current={tab==='summary'?'page':undefined} onClick={()=>setTab('summary')}>Summary</button><button className={tab==='checks'?'active':''} aria-current={tab==='checks'?'page':undefined} onClick={()=>setTab('checks')}>Checks & evidence<span>{tests.length}</span></button><button className={tab==='history'?'active':''} aria-current={tab==='history'?'page':undefined} onClick={()=>setTab('history')}>History</button></nav>
    {tab==='summary'&&<div className="desk-item-summary"><section><h3>What needs to happen</h3><p>{item.description||'Add a short description to give the team context.'}</p></section><section><h3>Acceptance criteria</h3><p>{item.acceptanceCriteria||'Define what must be true before the team accepts this work.'}</p></section><section><h3>Next action</h3><p>{item.nextAction||'No next action recorded yet.'}</p></section>{item.blocked&&item.stage!=='Closed'&&<section className="desk-blocker"><h3><AlertTriangle size={17}/>Blocker and help needed</h3><p>{item.blockReason}</p></section>}{item.evidenceLinks.length>0&&<section><h3>Linked references</h3><div className="stack">{item.evidenceLinks.map(link=><SafeLink key={link} href={link}/>)}</div></section>}<details className="desk-client-wording"><summary>Client report wording · {item.clientVisible?'Included in source selection':'Internal only'}</summary><p>{item.clientVisible?item.clientSummary||'Client-safe wording is still needed.':'This internal description is not included in client report source wording.'}</p></details></div>}
    {tab==='checks'&&<section ref={checksSection} className="desk-checks"><div className="desk-section-heading"><div><h3>Current delivery cycle {item.cycle}</h3><p className="muted">Only checks for the current cycle and stage can satisfy a handover.</p></div>{editable&&item.stage!=='Backlog'&&context!=='test'&&<button className="button secondary" onClick={()=>begin('test')}><Plus size={15}/>{['UAT','Production verification','Review'].includes(item.stage)?'Record check':'Record finding'}</button>}</div>{currentTests.map(renderTest)}{!currentTests.length&&<p className="desk-empty-record">No checks recorded for this cycle yet.</p>}{previousTests.length>0&&<details className="desk-previous-checks" open={priorUnresolved.length>0?true:undefined}><summary>Previous cycles · {previousTests.length} checks{priorUnresolved.length>0?' · '+priorUnresolved.length+' unresolved blocking':''}</summary>{priorUnresolved.length>0&&<p className="notice notice-warning">Blocking findings remain open until their resolution is recorded, including findings from earlier cycles.</p>}{previousTests.map(renderTest)}</details>}</section>}
    {tab==='history'&&<div className="desk-audit-timeline">{state.events.filter(e=>e.entityId===item.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(e=><article key={e.id}><span className="desk-timeline-dot"/><div><strong>{e.detail}</strong><p>{memberName(state,e.actorId)} · {new Date(e.createdAt).toLocaleString('en-GB',{timeZone:state.settings.timezone})}</p></div></article>)}<article><span className="desk-timeline-dot"/><div><strong>Work record created</strong><p>{formatDate(item.createdAt)}{item.importedFrom?' · Imported from '+item.importedFrom:''}</p></div></article></div>}
  </Modal>;
}

export function ItemForm({item,onClose,defaultWorkstream,embedded=false,...props}:PageProps&{item?:WorkItem;onClose:()=>void;defaultWorkstream?:string;embedded?:boolean}){
  const {state,user}=props;const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [reason,setReason]=useState('');
  const [links,setLinks]=useState(item?.evidenceLinks.join('\n')||'');const [editingVersion]=useState(item?.version);
  const availableStreams=state.workstreams.filter(w=>isPMO(user)||user.workstreamIds.includes(w.id)||w.id===item?.workstreamId);
  const initialStream=availableStreams.find(w=>w.id===defaultWorkstream)?.id||availableStreams[0]?.id||'';
  const allowed=item?canEditItem(state,user,item):canEdit(user)&&availableStreams.length>0;
  const [form,setForm]=useState<Partial<WorkItem>>(item||{title:'',description:'',workstreamId:initialStream,deliverableId:'',kind:'software',category:'feature',stage:'Backlog',priority:'Medium',ownerId:'',currentOwnerId:'',baselineDate:'',dueDate:'',acceptanceCriteria:'',nextAction:'',blocked:false,blockReason:'',clientVisible:false,clientSummary:'',tags:[]});
  const active=!!item&&item.stage!=='Backlog';const field=(key:keyof WorkItem,value:unknown)=>setForm(current=>({...current,[key]:value}));
  async function save(event:FormEvent){
    event.preventDefault();if(!allowed||busy)return;setBusy(true);setError('');
    try{
      const editableFields:(keyof WorkItem)[]=['title','description','workstreamId','deliverableId','category','priority','ownerId','currentOwnerId','dueDate','acceptanceCriteria','nextAction','blocked','blockReason','clientVisible','clientSummary','tags'];
      const data:Record<string,unknown>={};for(const key of editableFields)if(form[key]!==undefined)data[key]=form[key];
      data.evidenceLinks=links.split('\n').map(value=>value.trim()).filter(Boolean);
      if(!item){data.kind=form.kind;data.baselineDate=form.dueDate||'';}
      await props.mutate(item?'/api/records/items/'+item.id:'/api/items',item?{version:editingVersion,changes:data,reason}:data,item?'PATCH':'POST');
      props.notify(item?'Work details updated.':'Work captured in the backlog.');onClose();
    }catch(e){const message=(e as Error).message;setError(message);props.notify(message,true);}finally{setBusy(false);}
  }
  const content=<form onSubmit={save} onInvalid={event=>{const disclosure=(event.target as HTMLElement).closest('details');if(disclosure)disclosure.open=true;}} className="desk-capture-form">
    {error&&<div className="notice notice-warning" role="alert">{error}</div>}
    {!item&&<p className="desk-capture-intro">Capture the commitment now. Agree ownership, a target, and acceptance criteria before starting delivery.</p>}
    {!allowed&&<p className="notice">The accountable owner, current action owner, workstream lead, or PMO can edit this delivery record.</p>}
    <fieldset disabled={!allowed||busy} className="desk-fieldset">
      <Field label="What needs to be delivered?"><input autoFocus required value={form.title||''} onChange={e=>field('title',e.target.value)} placeholder="A clear outcome the team can act on"/></Field>
      <div className="form-grid"><Field label="Workstream"><select required value={form.workstreamId||''} onChange={e=>setForm({...form,workstreamId:e.target.value,deliverableId:''})}>{availableStreams.map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select></Field><Field label="Delivery workflow"><select disabled={!!item} value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as WorkflowKind,category:e.target.value==='general'?'action':'feature'})}><option value="software">Software change</option><option value="general">General work</option></select></Field></div>
      {!item&&<p className="desk-help">{form.kind==='software'?'Software changes progress through UAT, deployment, production verification, and client acceptance.':'Use general work for data, evaluations, research, and actions that finish with an internal review.'}</p>}
      <details className="desk-definition-group" open={item?true:undefined}><summary>Ownership & delivery definition<span>{item?'Review before the next handover':'Optional for capture'}</span></summary><div className="desk-disclosure-content"><p className="desk-help">The accountable owner owns the outcome. The next action owner is the person who moves it forward now.</p><div className="form-grid"><Field label="Accountable owner"><select required={active} value={form.ownerId||''} onChange={e=>field('ownerId',e.target.value)}><option value="">Unassigned</option>{state.members.filter(m=>m.role!=='executive').map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Next action owner"><select required={active} value={form.currentOwnerId||''} onChange={e=>field('currentOwnerId',e.target.value)}><option value="">Unassigned</option>{state.members.filter(m=>m.role!=='executive').map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Target date"><input type="date" required={active} value={form.dueDate||''} onChange={e=>field('dueDate',e.target.value)}/></Field><Field label="Priority"><select value={form.priority} onChange={e=>field('priority',e.target.value)}>{['Low','Medium','High','Critical'].map(value=><option key={value}>{value}</option>)}</select></Field></div><Field label="Context"><textarea rows={3} value={form.description||''} onChange={e=>field('description',e.target.value)} placeholder="What is the problem or intended outcome?"/></Field><Field label="Acceptance criteria"><textarea required={active} rows={3} value={form.acceptanceCriteria||''} onChange={e=>field('acceptanceCriteria',e.target.value)} placeholder="What must be true before the team can accept this?"/></Field><Field label="Next action"><input required={active||form.blocked} value={form.nextAction||''} onChange={e=>field('nextAction',e.target.value)} placeholder="The next concrete step"/></Field>{item?.dueDate&&form.dueDate!==item.dueDate&&<Field label="Why is the target date changing?"><input required value={reason} onChange={e=>setReason(e.target.value)}/></Field>}<label className="checkbox-label"><input type="checkbox" checked={!!form.blocked} onChange={e=>field('blocked',e.target.checked)}/>This work is blocked</label>{form.blocked&&<Field label="Blocker and help needed"><textarea required rows={2} value={form.blockReason||''} onChange={e=>field('blockReason',e.target.value)}/></Field>}</div></details>
      <details className="desk-definition-group"><summary>Links & classification<span>Deliverable, references, category</span></summary><div className="desk-disclosure-content"><div className="form-grid"><Field label="Linked deliverable"><select value={form.deliverableId||''} onChange={e=>field('deliverableId',e.target.value)}><option value="">No deliverable linked</option>{state.deliverables.filter(d=>d.workstreamId===form.workstreamId).map(d=><option value={d.id} key={d.id}>{d.title}</option>)}</select></Field><Field label="Category"><select value={form.category} onChange={e=>field('category',e.target.value)}>{['feature','bug','data','evaluation','action','research'].map(value=><option key={value} value={value}>{value.charAt(0).toUpperCase()+value.slice(1)}</option>)}</select></Field></div><Field label="Evidence links (one per line)"><textarea rows={3} value={links} onChange={e=>setLinks(e.target.value)} placeholder="https://…"/></Field></div></details>
      <details className="desk-definition-group" open={item?.clientVisible?true:undefined}><summary>Client report wording<span>{form.clientVisible?'Included in report source selection':'Internal by default'}</span></summary><div className="desk-disclosure-content"><label className="checkbox-label"><input type="checkbox" checked={!!form.clientVisible} onChange={e=>field('clientVisible',e.target.checked)}/>Include selected wording in client report sources</label>{form.clientVisible&&<Field label="Client-facing wording"><textarea required rows={3} value={form.clientSummary||''} onChange={e=>field('clientSummary',e.target.value)} placeholder="Describe progress in language suitable for the client."/></Field>}<p className="desk-help">Only this selected wording becomes client source content. Draft reports still need review and approval.</p></div></details>
    </fieldset><div className="form-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancel</button>{allowed&&<button className="button primary" disabled={busy}>{busy?'Saving…':item?'Save changes':'Capture work'}</button>}</div>
  </form>;
  return embedded?content:<Modal wide title={item?'Edit work details':'Capture new work'} description={item?item.id:'Start with the outcome and workstream.'} onClose={onClose}>{content}</Modal>;
}

export function MilestoneForm({milestone,onClose,...props}:PageProps&{milestone?:Milestone;onClose:()=>void}) {
  const {state,user,mutate,notify}=props;
  const [form,setForm]=useState<Partial<Milestone>>(milestone||{title:'',workstreamIds:[],deliverableIds:[],ownerId:user.id,baselineDate:'',forecastDate:'',status:'planned',notes:''});
  const [editingVersion]=useState(milestone?.version);
  const [reason,setReason]=useState('');
  const [busy,setBusy]=useState(false);
  const allowed=milestone?canEditOwnedRecord(state,user,milestone):isPMO(user);
  async function save(event:FormEvent) {
    event.preventDefault();if(!allowed||busy)return;setBusy(true);
    try {
      const data={title:form.title,workstreamIds:form.workstreamIds,deliverableIds:form.deliverableIds,ownerId:form.ownerId,forecastDate:form.forecastDate,status:form.status,notes:form.notes,...(form.actualDate?{actualDate:form.actualDate}:{}),...(!milestone?{baselineDate:form.baselineDate}:{})};
      await mutate(milestone?`/api/records/milestones/${milestone.id}`:'/api/records/milestones',milestone?{version:editingVersion,changes:data,reason}:data,milestone?'PATCH':'POST');
      notify('Milestone saved');onClose();
    }catch(error){notify((error as Error).message,true);}finally{setBusy(false);}
  }
  return <Modal title={milestone?'Milestone outlook':'New milestone'} onClose={onClose}><form onSubmit={save}>
    <fieldset disabled={!allowed||busy} style={{border:0,padding:0,margin:0,minWidth:0}}>
      <Field label="Milestone"><input required value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></Field>
      <div className="form-grid">
        <Field label="Owner"><select required value={form.ownerId} onChange={event=>setForm({...form,ownerId:event.target.value})}>{state.members.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></Field>
        <Field label="Status"><select value={form.status} onChange={event=>setForm({...form,status:event.target.value as Milestone['status']})}><option value="planned">Planned</option><option value="at_risk">At risk</option><option value="complete">Complete</option></select></Field>
        <Field label="Baseline date"><input type="date" required disabled={!!milestone} value={form.baselineDate} onChange={event=>setForm({...form,baselineDate:event.target.value,forecastDate:form.forecastDate||event.target.value})}/></Field>
        <Field label="Forecast date"><input type="date" required value={form.forecastDate} onChange={event=>setForm({...form,forecastDate:event.target.value})}/></Field>
        {form.status==='complete'&&<Field label="Actual completion"><input type="date" required value={form.actualDate||''} onChange={event=>setForm({...form,actualDate:event.target.value})}/></Field>}
      </div>
      <div className="field"><span>Contributing workstreams</span><div className="checkbox-list">{state.workstreams.map(stream=><label className="checkbox-label" key={stream.id}><input type="checkbox" checked={form.workstreamIds?.includes(stream.id)||false} onChange={event=>setForm({...form,workstreamIds:event.target.checked?[...(form.workstreamIds||[]),stream.id]:(form.workstreamIds||[]).filter(id=>id!==stream.id)})}/>{stream.name}</label>)}</div></div>
      <div className="field"><span>Linked deliverables</span><div className="checkbox-list">{state.deliverables.map(deliverable=><label className="checkbox-label" key={deliverable.id}><input type="checkbox" checked={form.deliverableIds?.includes(deliverable.id)||false} onChange={event=>setForm({...form,deliverableIds:event.target.checked?[...(form.deliverableIds||[]),deliverable.id]:(form.deliverableIds||[]).filter(id=>id!==deliverable.id)})}/>{deliverable.title}</label>)}</div></div>
      <Field label="Outlook and context"><textarea rows={3} value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})}/></Field>
      {milestone&&form.forecastDate!==milestone.forecastDate&&<Field label="Reason for forecast change"><input required value={reason} onChange={event=>setReason(event.target.value)}/></Field>}
    </fieldset>
    <div className="form-actions"><button className="button secondary" type="button" onClick={onClose}>Close</button>{allowed&&<button className="button primary" disabled={busy||!form.workstreamIds?.length}>{busy?'Saving…':'Save milestone'}</button>}</div>
  </form></Modal>;
}

function DeliverableForm({value,onClose,...props}:PageProps&{value?:Deliverable;onClose:()=>void}) {
  const {state,user,mutate,notify}=props;
  const availableStreams=state.workstreams.filter(stream=>isPMO(user)||user.workstreamIds.includes(stream.id)||stream.id===value?.workstreamId);
  const [form,setForm]=useState({title:value?.title||'',description:value?.description||'',workstreamId:value?.workstreamId||availableStreams[0]?.id||'',ownerId:value?.ownerId||user.id});
  const [editingVersion]=useState(value?.version);
  const [busy,setBusy]=useState(false);
  const allowed=value?canEditOwnedRecord(state,user,value):canEdit(user)&&availableStreams.length>0;
  async function save(event:FormEvent) {
    event.preventDefault();if(!allowed||busy)return;setBusy(true);
    try {await mutate(value?`/api/records/deliverables/${value.id}`:'/api/records/deliverables',value?{version:editingVersion,changes:form}:form,value?'PATCH':'POST');notify('Deliverable saved');onClose();}
    catch(error){notify((error as Error).message,true);}finally{setBusy(false);}
  }
  return <Modal title={value?'Edit deliverable':'New deliverable'} onClose={onClose}><form onSubmit={save}>
    <fieldset disabled={!allowed||busy} style={{border:0,padding:0,margin:0,minWidth:0}}>
      <Field label="Deliverable"><input required value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></Field>
      <Field label="Workstream"><select required value={form.workstreamId} onChange={event=>setForm({...form,workstreamId:event.target.value})}>{availableStreams.map(stream=><option value={stream.id} key={stream.id}>{stream.name}</option>)}</select></Field>
      <Field label="Owner"><select required value={form.ownerId} onChange={event=>setForm({...form,ownerId:event.target.value})}>{state.members.map(member=><option value={member.id} key={member.id}>{member.name}</option>)}</select></Field>
      <Field label="Outcome"><textarea rows={3} required value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></Field>
    </fieldset>
    <div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button>{allowed&&<button className="button primary" disabled={busy}>{busy?'Saving…':'Save deliverable'}</button>}</div>
  </form></Modal>;
}
function ImportDialog({onClose,...props}:PageProps&{onClose:()=>void}) {const [preview,setPreview]=useState<ImportPreview>();const [file,setFile]=useState<{filename:string;content:string}>();const [busy,setBusy]=useState(false);const [mapping,setMapping]=useState<Record<string,string>>({});const [error,setError]=useState('');
  async function makePreview(input:typeof file,map?:Record<string,string>){if(!input)return;setBusy(true);setError('');try{const result=await props.mutate('/api/import/preview',{...input,mapping:map});setPreview(result);setMapping(result.mapping);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal wide title="Bring your backlog into the hub" description="Map your Excel or CSV columns, review the rows, then import." onClose={onClose}><div className="import-drop"><Upload size={27}/><strong>Choose an Excel workbook or CSV file</strong><p>Work items import into Backlog unless you explicitly map an existing stage.</p><input aria-label="Select backlog file" type="file" accept=".xlsx,.csv" disabled={busy} onChange={async e=>{const selected=e.target.files?.[0];if(!selected)return;if(selected.size>5*1024*1024){setError('Choose a file smaller than 5 MB.');return;}const reader=new FileReader();reader.onload=()=>{const input={filename:selected.name,content:String(reader.result).split(',')[1]};setFile(input);makePreview(input);};reader.readAsDataURL(selected);}}/></div>{error&&<div className="notice notice-warning">{error}</div>}{busy&&<p className="muted" role="status">Reading your backlog…</p>}{preview&&<><h3>Column mapping</h3><div className="form-grid">{['title','description','workstreamId','ownerId','currentOwnerId','dueDate','stage','kind','priority','acceptanceCriteria','nextAction'].map(field=><Field key={field} label={field.replace(/([A-Z])/g,' $1')}><select value={mapping[field]||''} onChange={e=>setMapping({...mapping,[field]:e.target.value})}><option value="">Not mapped</option>{preview.headers.map(h=><option key={h}>{h}</option>)}</select></Field>)}</div><button className="button secondary" disabled={busy} onClick={()=>makePreview(file,mapping)}>Update preview</button><div className="import-summary"><Badge tone="green">{preview.validCount} valid</Badge><Badge tone="amber">{preview.invalidCount} need attention</Badge><Badge>{preview.duplicateCount} duplicates</Badge></div><div className="table-scroll import-preview"><table className="data-table"><thead><tr><th>Row</th><th>Work item</th><th>Review</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.line}><td>{row.line}</td><td>{row.item.title||'Missing title'}</td><td>{row.duplicate?'Already in the hub':row.errors.length?row.errors.join(' · '):'Ready to import'}</td></tr>)}</tbody></table></div><p className="muted">Only valid, non-duplicate rows are imported. Existing completion stages retain import provenance; no testing evidence is invented.</p><div className="form-actions"><a className="button ghost" href="/api/export?format=csv" download>Download current backlog as an example</a><button className="button primary" disabled={busy||!preview.validCount||JSON.stringify(mapping)!==JSON.stringify(preview.mapping)} onClick={async()=>{setBusy(true);try{const result=await props.mutate('/api/import/commit',{previewId:preview.id});props.notify(`Backlog imported: ${result.importedCount} items${result.skippedCount ? ` · ${result.skippedCount} skipped` : ''}`);onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Import {preview.validCount} valid rows</button></div></>}</Modal>;
}
