import { useState } from 'react';
import { Search } from 'lucide-react';
import type { PageProps, Workstream } from '../shared/types';
import { Avatar, Badge, Field, Modal, healthLabel, formatDate, memberName } from './ui';
export function WorkstreamEditor({id,onClose,...props}:PageProps&{id:string;onClose:()=>void}) {
  const original=props.state.workstreams.find(w=>w.id===id);const isPMO=['pmo','admin'].includes(props.user.role);const editable=isPMO||!!original&&original.leadId===props.user.id;
  const [form,setForm]=useState<Partial<Workstream>>(original||{name:'',shortName:'',description:'',leadId:props.state.members.find(m=>m.role==='lead')?.id||props.user.id,health:'unknown',statusNote:'',clientSummary:'',color:'#8061ce'});const [busy,setBusy]=useState(false);const [editingVersion]=useState(original?.version);
  return <Modal title={original?.name||'New workstream'} description="A shared delivery outcome with an accountable lead." onClose={onClose}><form onSubmit={async e=>{e.preventDefault();if(!editable||busy)return;setBusy(true);try{await props.mutate(original?`/api/records/workstreams/${id}`:'/api/records/workstreams',original?{version:editingVersion,changes:form,reason:'Workstream review'}:form,original?'PATCH':'POST');props.notify(original?'Workstream updated':'Workstream created');onClose();}catch(e){props.notify((e as Error).message,true);}finally{setBusy(false);}}}>
    <div className="form-grid"><Field label="Workstream name"><input required disabled={!editable} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Short label"><input required maxLength={24} disabled={!editable} value={form.shortName} onChange={e=>setForm({...form,shortName:e.target.value})}/></Field><Field label="Accountable lead"><select disabled={!editable} value={form.leadId} onChange={e=>setForm({...form,leadId:e.target.value})}>{props.state.members.filter(m=>['lead','pmo','admin'].includes(m.role)).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Delivery health"><select disabled={!editable} value={form.health} onChange={e=>setForm({...form,health:e.target.value as any})}>{Object.entries(healthLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field></div><Field label="Purpose"><textarea disabled={!editable} rows={2} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Assessment and supporting rationale"><textarea required={form.health!=='unknown'} disabled={!editable} rows={3} value={form.statusNote} onChange={e=>setForm({...form,statusNote:e.target.value})}/></Field><Field label="Client-facing summary"><textarea disabled={!editable} rows={3} value={form.clientSummary} onChange={e=>setForm({...form,clientSummary:e.target.value})}/></Field><div className="health-guide"><div><Badge tone="green">On track</Badge><span>The committed outcome remains achievable.</span></div><div><Badge tone="amber">At risk</Badge><span>A threat needs a recovery action.</span></div><div><Badge tone="red">Off track</Badge><span>A commitment is missed or delivery needs intervention.</span></div></div>{original&&<p className="muted small-text">Last reviewed {formatDate(original.updatedAt)}. Missing or stale weekly submissions are shown separately.</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Close</button>{editable&&<button className="button primary" disabled={busy}>{busy?'Saving…':original?'Save assessment':'Create workstream'}</button>}</div></form></Modal>;
}
export function AuditHistory({onClose,...props}:PageProps&{onClose:()=>void}) {
  const [query,setQuery]=useState('');const [person,setPerson]=useState('all');const events=[...props.state.events].filter(e=>(person==='all'||e.actorId===person)&&[e.detail,e.entityId,e.action,memberName(props.state,e.actorId)].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  return <Modal wide title="Project activity" description="A searchable history of assignments, delivery, reviews, and reporting." onClose={onClose}><div className="toolbar"><div className="search-input"><Search size={17}/><input aria-label="Search project history" placeholder="Find an item, change, or decision…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filter history by person" value={person} onChange={e=>setPerson(e.target.value)}><option value="all">Everyone</option>{props.state.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><span className="muted">{events.length} events</span></div><div className="audit-timeline">{events.slice(0,200).map(e=><article key={e.id}><Avatar member={props.state.members.find(m=>m.id===e.actorId)} size={28}/><div><strong>{e.detail}</strong><p>{memberName(props.state,e.actorId)} · {new Date(e.createdAt).toLocaleString('en-GB',{timeZone:props.state.settings.timezone})} · {e.entityType}</p><span className="item-ref">{e.entityId}</span></div></article>)}</div>{!events.length&&<div className="empty-state">No changes match your search.</div>}</Modal>;
}
