import { useState } from 'react';
import { Search } from 'lucide-react';
import { LIFECYCLE_PHASES, type Health, type PageProps } from '../shared/types';
import { Avatar, Badge, Field, Modal, healthLabel, formatDate, memberName } from './ui';
import { canEditUseCase, phaseGuidance, phaseLabels, type LifecyclePhase } from './portfolio-model';
export function WorkstreamEditor({id,onClose,...props}:PageProps&{id:string;onClose:()=>void}) {
  const original=props.state.workstreams.find(workstream=>workstream.id===id);
  const editable=canEditUseCase(props.user,original);
  const [form,setForm]=useState({name:original?.name||'',shortName:original?.shortName||'',description:original?.description||'',leadId:original?.leadId||'',health:original?.health||'unknown',statusNote:original?.statusNote||'',clientSummary:original?.clientSummary||'',color:original?.color||'#8600d6',lifecyclePhase:original?.lifecyclePhase||'',priority:original?.priority||'',scope:original?.scope||'',nextGate:original?.nextGate||'',gateDate:original?.gateDate||''});
  const [busy,setBusy]=useState(false);const [editingVersion]=useState(original?.version);const [error,setError]=useState('');
  return <Modal wide title={original?.name||'New use case'} description="Record the confirmed brief, lifecycle position and next gate. Details can be added as they become known." onClose={()=>!busy&&onClose()}><form onSubmit={async event=>{
    event.preventDefault();if(!editable||busy)return;setBusy(true);setError('');
    const changes={...form,name:form.name.trim(),shortName:form.shortName.trim()||form.name.trim().slice(0,24),lifecyclePhase:form.lifecyclePhase||null,priority:form.priority||null};
    try{await props.mutate(original?`/api/records/workstreams/${id}`:'/api/records/workstreams',original?{version:editingVersion,changes,reason:'Use-case profile updated'}:changes,original?'PATCH':'POST');props.notify(original?'Use-case profile updated':'Use case created');onClose();}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}
  }}>
    <fieldset disabled={!editable||busy} style={{border:0,padding:0,margin:0,minWidth:0}}>
      <div className="form-grid"><Field label="Use-case name"><input required maxLength={240} value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></Field><Field label="Short label · optional"><input maxLength={24} value={form.shortName} onChange={event=>setForm({...form,shortName:event.target.value})}/></Field></div>
      <Field label="Intended outcome"><textarea rows={3} value={form.description} onChange={event=>setForm({...form,description:event.target.value})} placeholder="What outcome should this use case achieve?"/></Field>
      <Field label="Scope"><textarea rows={3} value={form.scope} onChange={event=>setForm({...form,scope:event.target.value})} placeholder="What is included, and what sits outside this use case?"/></Field>
      <div className="form-grid"><Field label="Accountable lead"><select value={form.leadId} onChange={event=>setForm({...form,leadId:event.target.value})}><option value="">Not yet set</option>{props.state.members.filter(member=>['lead','pmo','admin'].includes(member.role)||member.id===form.leadId).map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></Field><Field label="Priority"><select value={form.priority} onChange={event=>setForm({...form,priority:event.target.value})}><option value="">Not yet set</option>{['Low','Medium','High','Critical'].map(priority=><option key={priority}>{priority}</option>)}</select></Field></div>
      <Field label="Lifecycle phase"><select value={form.lifecyclePhase} onChange={event=>setForm({...form,lifecyclePhase:event.target.value})}><option value="">Not yet set</option>{LIFECYCLE_PHASES.map(phase=><option key={phase} value={phase}>{phaseLabels[phase]}</option>)}</select></Field>
      {form.lifecyclePhase&&<p className="muted small-text" style={{margin:'-8px 0 20px'}}>{phaseGuidance[form.lifecyclePhase as LifecyclePhase]}</p>}
      <div className="form-grid"><Field label="Next gate"><input value={form.nextGate} onChange={event=>setForm({...form,nextGate:event.target.value})} placeholder="The next review or decision"/></Field><Field label="Gate target date"><input type="date" value={form.gateDate} onChange={event=>setForm({...form,gateDate:event.target.value})}/></Field></div>
      <details open={form.health!=='unknown'||undefined} className="profile-assessment"><summary style={{cursor:'pointer',padding:'10px 0',fontWeight:600}}>Delivery assessment and client summary</summary><div style={{paddingTop:14}}>
        <Field label="Delivery assessment"><select value={form.health} onChange={event=>setForm({...form,health:event.target.value as Health})}>{Object.entries(healthLabel).map(([value,label])=><option key={value} value={value}>{value==='unknown'?'Not yet set':label}</option>)}</select></Field>
        <Field label="Assessment and supporting rationale"><textarea required={form.health!=='unknown'} rows={3} value={form.statusNote} onChange={event=>setForm({...form,statusNote:event.target.value})}/></Field>
        <Field label="Client-facing summary"><textarea rows={3} value={form.clientSummary} onChange={event=>setForm({...form,clientSummary:event.target.value})}/></Field>
        <div className="health-guide"><div><Badge tone="green">On track</Badge><span>The committed outcome remains achievable.</span></div><div><Badge tone="amber">At risk</Badge><span>A threat needs a recovery action.</span></div><div><Badge tone="red">Off track</Badge><span>A commitment is missed or delivery needs intervention.</span></div></div>
      </div></details>
    </fieldset>
    {error&&<div className="notice notice-warning" role="alert">{error}</div>}
    {original&&<p className="muted small-text" style={{marginTop:15}}>Profile updated {formatDate(original.updatedAt)}. Weekly confirmation is recorded separately.</p>}
    <div className="form-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>{editable?'Cancel':'Close'}</button>{editable&&<button className="button primary" disabled={busy}>{busy?'Saving…':original?'Save profile':'Create use case'}</button>}</div>
  </form></Modal>;
}
export function AuditHistory({onClose,...props}:PageProps&{onClose:()=>void}) {
  const [query,setQuery]=useState('');const [person,setPerson]=useState('all');const events=[...props.state.events].filter(e=>(person==='all'||e.actorId===person)&&[e.detail,e.entityId,e.action,memberName(props.state,e.actorId)].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  return <Modal wide title="Project activity" description="A searchable history of assignments, delivery, reviews, and reporting." onClose={onClose}><div className="toolbar"><div className="search-input"><Search size={17}/><input aria-label="Search project history" placeholder="Find an item, change, or decision…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filter history by person" value={person} onChange={e=>setPerson(e.target.value)}><option value="all">Everyone</option>{props.state.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><span className="muted">{events.length} events</span></div><div className="audit-timeline">{events.slice(0,200).map(e=><article key={e.id}><Avatar member={props.state.members.find(m=>m.id===e.actorId)} size={28}/><div><strong>{e.detail}</strong><p>{memberName(props.state,e.actorId)} · {new Date(e.createdAt).toLocaleString('en-GB',{timeZone:props.state.settings.timezone})} · {e.entityType}</p><span className="item-ref">{e.entityId}</span></div></article>)}</div>{!events.length&&<div className="empty-state">No changes match your search.</div>}</Modal>;
}
