import { useMemo, useState } from 'react';
import { AlertCircle, ArrowUpRight, ChevronDown, ChevronRight, FileSpreadsheet, FileText, FolderOpen, Link2, Search, X } from 'lucide-react';
import type { PageProps, SourceDocument, SourceRecord } from '../shared/types';
import { formatDate } from './ui';
import './sources.css';

const dispositionLabels: Record<SourceRecord['disposition'], string> = {
  active: 'Active in source', completed: 'Resolved / closed in source', needs_review: 'Needs review', excluded: 'Deferred / excluded',
};
const coverageLabels: Record<SourceDocument['coverage'], string> = { current: 'Current tracker coverage', context: 'Historical / project context', unavailable: 'Material unavailable' };
const stated = (value?: string) => value?.trim() || 'Not stated';
const sourceDate = (value?: string, timezone = 'Asia/Dubai') => value ? formatDate(value, { day: 'numeric', month: 'short', year: 'numeric', timeZone: timezone }) : 'Date not stated';

export default function Sources({ state, openItem }: PageProps) {
  const documents = state.sourceDocuments || [];
  const records = state.sourceRecords || [];
  const [documentId, setDocumentId] = useState('all');
  const [workstreamId, setWorkstreamId] = useState('all');
  const [disposition, setDisposition] = useState('all');
  const [query, setQuery] = useState('');
  const [selectedId, setSelectedId] = useState<string>();
  const documentById = useMemo(() => new Map(documents.map(document => [document.id, document])), [documents]);
  const currentTrackers = documents.filter(document => document.kind === 'tracker' && document.coverage === 'current');
  const currentTrackerIds = new Set(currentTrackers.map(document => document.id));
  const currentRows = records.filter(record => currentTrackerIds.has(record.documentId));
  const unavailable = documents.filter(document => document.coverage === 'unavailable' || document.kind === 'unavailable');
  const visible = records.filter(record => {
    const workstream = state.workstreams.find(value => value.id === record.workstreamId);
    return (documentId === 'all' || record.documentId === documentId) && (workstreamId === 'all' || (workstreamId === 'unmapped' ? !record.workstreamId : record.workstreamId === workstreamId)) && (disposition === 'all' || record.disposition === disposition) &&
      [record.title, record.detail, record.locator, record.sourceKey, record.sourceStatus, record.sourceOwner, record.sourcePriority, record.sourceDates, record.resolutionNotes, record.mappingNote, record.syncNote, documentById.get(record.documentId)?.name, workstream?.name].join(' ').toLowerCase().includes(query.trim().toLowerCase());
  }).sort((a, b) => (documentById.get(a.documentId)?.name || '').localeCompare(documentById.get(b.documentId)?.name || '') || a.locator.localeCompare(b.locator, undefined, { numeric: true }) || a.sourceKey.localeCompare(b.sourceKey));
  const selected = visible.find(record => record.id === selectedId) || visible[0];
  const selectedDocument = documentById.get(documentId);
  const filtered = documentId !== 'all' || workstreamId !== 'all' || disposition !== 'all' || !!query.trim();
  function clearFilters() { setDocumentId('all'); setWorkstreamId('all'); setDisposition('all'); setQuery(''); }
  function chooseDocument(id: string) { setDocumentId(id); setWorkstreamId('all'); setDisposition('all'); setQuery(''); }

  return <div className="sources-workspace">
    <header className="sources-header"><div><span className="sources-kicker">The record behind the plan</span><h1>Sources & project context</h1><p>Original tracker facts and steering material, connected to the work in this hub.</p></div><div className="sources-header-count"><strong>{currentRows.length}</strong><span>current tracker rows<br/>from {currentTrackers.length} {currentTrackers.length === 1 ? 'tracker' : 'trackers'}</span></div></header>

    {unavailable.length > 0 && <details className="sources-availability"><summary><AlertCircle size={18}/><span>{unavailable.length} {unavailable.length === 1 ? 'source material is' : 'source materials are'} unavailable</span><ChevronDown size={16}/></summary><div>{unavailable.map(document => <section key={document.id}><strong>{document.name}</strong><p>{document.summary || 'This material could not be read.'}</p>{document.warnings.map((warning, index) => <p key={index}>{warning}</p>)}</section>)}<p className="sources-reexport-note">Provide the original document or re-export the files individually to complete this context.</p></div></details>}

    <details className="sources-library" open={!records.length || undefined}><summary><FolderOpen size={18}/><strong>Source material</strong><span>{documents.length} {documents.length === 1 ? 'document' : 'documents'} · {documents.filter(document => document.coverage === 'context').length} for project context</span><ChevronDown size={17}/></summary><div className="sources-document-grid">{documents.map(document => <button key={document.id} className={`sources-document ${documentId === document.id ? 'is-selected' : ''}`} aria-pressed={documentId === document.id} onClick={() => chooseDocument(document.id)}>{document.kind === 'tracker' ? <FileSpreadsheet size={23}/> : <FileText size={23}/>}<span className={`sources-coverage coverage-${document.coverage}`}>{coverageLabels[document.coverage]}</span><strong>{document.name}</strong><span>{sourceDate(document.sourceDate, state.settings.timezone)}</span><p>{document.summary || 'Summary not stated'}</p><span className="sources-document-footer">{records.filter(record => record.documentId === document.id).length} source rows{document.warnings.length ? ` · ${document.warnings.length} source notes` : ''}<ChevronRight size={15}/></span></button>)}{!documents.length && <div className="sources-empty"><FileText size={26}/><h2>No source material loaded yet</h2><p>Imported tracker rows and supporting project documents will appear here with their source references.</p></div>}</div></details>

    <div className="sources-counts" aria-label="Filter by source record disposition"><button className={disposition === 'all' ? 'is-active' : ''} aria-pressed={disposition === 'all'} onClick={() => setDisposition('all')}><strong>{records.length}</strong><span>All source rows</span></button>{(['active', 'completed', 'needs_review', 'excluded'] as const).map(value => <button key={value} className={disposition === value ? 'is-active' : ''} aria-pressed={disposition === value} onClick={() => setDisposition(disposition === value ? 'all' : value)}><strong>{records.filter(record => record.disposition === value).length}</strong><span>{dispositionLabels[value]}</span></button>)}</div>

    <section className="sources-register" aria-labelledby="source-rows-heading"><div className="sources-section-heading"><h2 id="source-rows-heading">Source records</h2><p>Source status and hub delivery stage are shown separately.</p></div>
      <div className="sources-filters"><div className="search-input"><Search size={18}/><input value={query} aria-label="Search source records" placeholder="Find a task, source status, owner or comment…" onChange={event => setQuery(event.target.value)}/>{query && <button className="icon-button" aria-label="Clear source search" onClick={() => setQuery('')}><X size={16}/></button>}</div><label>Document<select value={documentId} onChange={event => setDocumentId(event.target.value)}><option value="all">All documents</option>{documents.map(document => <option key={document.id} value={document.id}>{document.name}</option>)}</select></label><label>Use case<select value={workstreamId} onChange={event => setWorkstreamId(event.target.value)}><option value="all">All use cases</option><option value="unmapped">Not yet mapped</option>{[...state.workstreams].sort((a, b) => a.name.localeCompare(b.name)).map(stream => <option key={stream.id} value={stream.id}>{stream.name}</option>)}</select></label><label>Disposition<select value={disposition} onChange={event => setDisposition(event.target.value)}><option value="all">All source rows</option>{Object.entries(dispositionLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
      {selectedDocument && <div className="sources-filter-document"><div><span className={`sources-coverage coverage-${selectedDocument.coverage}`}>{coverageLabels[selectedDocument.coverage]}</span><strong>{selectedDocument.name}</strong><p>{selectedDocument.summary}</p><span>Source date: {sourceDate(selectedDocument.sourceDate, state.settings.timezone)} · Received: {sourceDate(selectedDocument.receivedAt, state.settings.timezone)}</span>{selectedDocument.warnings.map((warning, index) => <p className="sources-inline-warning" key={index}>{warning}</p>)}</div><button className="text-button" onClick={() => setDocumentId('all')}>All documents <X size={14}/></button></div>}
      <div className="sources-results"><span role="status">{visible.length} of {records.length} source rows</span>{filtered && <button className="text-button" onClick={clearFilters}>Clear filters <X size={14}/></button>}</div>
      <div className={`sources-layout ${selected ? '' : 'no-selection'}`}><div className="sources-row-list">{visible.map(record => {
        const stream = state.workstreams.find(value => value.id === record.workstreamId);
        const document = documentById.get(record.documentId);
        return <button key={record.id} className={`sources-row ${selected?.id === record.id ? 'is-selected' : ''}`} aria-pressed={selected?.id === record.id} aria-controls="source-record-detail" onClick={() => setSelectedId(record.id)}><span className="sources-row-main"><span className="sources-row-location">{document?.name || 'Document unavailable'} · {record.locator}</span><strong>{record.title}</strong><span className="sources-row-case">{stream?.name || 'Use case not yet mapped'}</span>{record.syncNote && <span className="sources-row-review">Source update requires review</span>}</span><span className="sources-row-state"><span>Source status</span><strong>{stated(record.sourceStatus)}</strong><span className={`sources-disposition disposition-${record.disposition}`}>{dispositionLabels[record.disposition]}</span></span><ChevronRight size={17}/></button>;
      })}{!visible.length && <div className="sources-empty"><Search size={26}/><h3>{records.length ? 'No source rows match this view' : 'No tracker rows loaded yet'}</h3><p>{selectedDocument?.coverage === 'context' ? 'This document provides project context. Its use-case references remain visible in the portfolio.' : filtered ? 'Try another source document, use case or search term.' : 'The source library above shows the material available so far.'}</p>{filtered && <button className="button secondary" onClick={clearFilters}>Show all source rows</button>}</div>}</div>
        {selected && <SourceDetail key={selected.id} record={selected} document={documentById.get(selected.documentId)} state={state} openItem={openItem}/>}
      </div>
    </section>
  </div>;
}

function SourceDetail({ record, document, state, openItem }: { record: SourceRecord; document?: SourceDocument; state: PageProps['state']; openItem: PageProps['openItem'] }) {
  const stream = state.workstreams.find(value => value.id === record.workstreamId);
  const item = state.items.find(value => value.id === record.itemId);
  const matchesDocumentRevision = !record.fileHash || record.fileHash === document?.fileHash;
  return <aside className="sources-detail" id="source-record-detail" aria-label={`${record.title}: source record`}><header><span className={`sources-disposition disposition-${record.disposition}`}>{dispositionLabels[record.disposition]}</span><h2>{record.title}</h2><p>{stream?.name || 'Use case not yet mapped'}</p>{item && <button className="button primary" onClick={() => openItem(item.id)}>{record.disposition === 'needs_review' ? 'Open status follow-up' : 'Open linked work'} <ArrowUpRight size={16}/></button>}</header><div className="sources-detail-body">
    <section className="sources-original-status"><span>Original source status</span><strong>{stated(record.sourceStatus)}</strong>{item && <p>Hub stage: <b>{item.stage === 'Backlog' && item.importedFrom ? 'Intake / Backlog' : item.stage}</b></p>}</section>
    {record.disposition === 'completed' && <p className="sources-context-note">Completion is reported by the source. It is not a recorded PMO acceptance or test result.</p>}
    {(record.disposition === 'needs_review' || record.syncNote) && <div className="sources-review-note"><AlertCircle size={17}/><div><strong>Review the source mapping</strong><p>{record.syncNote || record.mappingNote || 'This row needs a mapping decision before it can become delivery work.'}</p></div></div>}
    <dl className="sources-original-fields"><div><dt>Source owner</dt><dd>{stated(record.sourceOwner)}</dd></div><div><dt>Source priority</dt><dd>{stated(record.sourcePriority)}</dd></div><div className="sources-field-wide"><dt>Dates stated in the source</dt><dd>{stated(record.sourceDates)}</dd></div></dl>
    <section className="sources-detail-section"><h3>Original detail</h3><p>{stated(record.detail)}</p></section><section className="sources-detail-section"><h3>Resolution notes / comments</h3><p>{stated(record.resolutionNotes)}</p></section>
    <section className="sources-mapping"><div><Link2 size={17}/><h3>Connection to the hub</h3></div><p>{stated(record.mappingNote)}</p>{item ? <dl><div><dt>Linked work</dt><dd>{item.title}</dd></div><div><dt>Current action owner</dt><dd>{state.members.find(member => member.id === item.currentOwnerId)?.name || 'Not yet set'}</dd></div><div><dt>Hub target date</dt><dd>{item.dueDate ? sourceDate(item.dueDate, state.settings.timezone) : 'Not yet set'}</dd></div></dl> : <p className="sources-unlinked">{record.disposition === 'completed' ? 'Retained as a source record; no active delivery item.' : record.disposition === 'excluded' ? 'Retained for context; excluded from delivery work.' : record.itemId ? 'The linked work item is not available in this workspace.' : 'No delivery item linked yet.'}</p>}</section>
    <section className="sources-provenance"><h3>Source reference</h3><strong>{document?.name || 'Document unavailable'}</strong><p>{record.locator || 'Location not stated'}</p>{!matchesDocumentRevision && <p>{document?.fileHash ? 'Earlier source revision.' : 'Pinned source revision.'} The source and received dates for this revision were not recorded.</p>}{matchesDocumentRevision && <><dl><div><dt>Source date</dt><dd>{sourceDate(document?.sourceDate, state.settings.timezone)}</dd></div><div><dt>Received</dt><dd>{sourceDate(document?.receivedAt, state.settings.timezone)}</dd></div></dl>{document && <span className={`sources-coverage coverage-${document.coverage}`}>{coverageLabels[document.coverage]}</span>}{document?.warnings.map((warning, index) => <p className="sources-inline-warning" key={index}>{warning}</p>)}</>}<details><summary>Source identifiers <ChevronDown size={14}/></summary><span>Record key</span><code>{record.sourceKey}</code>{(record.fileHash || document?.fileHash) && <><span>{record.fileHash ? 'Pinned file fingerprint' : 'File fingerprint'}</span><code>{record.fileHash || document?.fileHash}</code></>}</details></section>
  </div></aside>;
}
